- config/mysql-config/my.cnf
When adding databases to the engine, MySQL adds them all to
the _same_ file by default (in < 5.6.6). When removing these databases
later, MySQL fails to truncate the file, leading to used disk space that's
not actually being used. By specifying one file per table, end users can
more easily free disk space when projects are archived/removed.
Also note, this is a feature that is on by default in MySQL >= 5.6.6, so
we might as well bake it in now to get the management benefits and get
everyone ready for an eventual version update.
Fixes #537
> Use single files per table

- Vagrantfile
- provision/provision.sh
Parallels Desktop offers an official and open-source Vagrant Provider plugin at http://parallels.github.io/vagrant-parallels/ and https://github.com/Parallels/vagrant-parallels.
The only real differences to our Virtualbox configuration that I have spotted after a quick glance are the box name and the way how machine settings are changed. Both of this can be overridden with provider-specific declarations in the Vagrantfile, as far as I can see.
I'll use this as a tracking issue for my experiments with adding support to VVV.
> Support for Parallels Desktop

- provision/provision.sh
Quoting prevents word splitting and glob expansion, and prevents the script from breaking when input contains spaces, line feeds, glob characters and such.
If `var=my value`, the space is retained with quoting. Otherwise it will split and provide unexpected results. Nothing in the provision script is currently broken, its just a best practice to do it this way.
> Quote a few variables in provision.sh

- provision/provision.sh
Defining `WP_HOME` and `WP_SITEURL` when an xip.io request comes in allows all parts of the site to function as normal rather than in a hybrid mode.
> [PR] Provide better xip.io support in wp-config.php

- Vagrantfile
* Provides details for port forwarding, inspired by @salcode's #445.
* Renames "External IP Address" example to "Public Network"
* Update documentation for public and private networks.
> [PR] Update inline documentation around private networking, public networking, and port forwarding

- provision/provision.sh
If a new version of Akismet is shipped let `svn up` grab that latest version for WordPress `/trunk`
> Don't ignore SVN externals for WordPress /trunk

- provision/provision.sh
See https://www.npmjs.org/package/npm-check-updates
The module is useful to quickly check for updated Grunt modules in a package.json.
Used by @ocean90 as well: https://core.trac.wordpress.org/ticket/27340#comment:16 :-)
> Install the `npm-check-updates` module during provisioning

- config/init/mailcatcher.conf
- config/init/vvv-start.conf
- config/php5-fpm-config/mailcatcher.ini
- provision/provision.sh
- www/default/index.php
This PR replaces #464 
This is based off of the `develop` branch and should be used instead.
Includes:
RVM install
mailcatcher install
startup script
PHP smtp configuration
dashboard link to port
Later revisions also did the following:
Fixes issues with signature checks in the RVM installation process.
Removed the stopgap fix for i18n dependency issues of past.
Added blank lines per request.
> Adds mailcatcher support.

- README.md
There was a typo in 'helpful' unless it's some obscure pun. Tiny change but reads better.
> fix typo on "helpful" header in readme

- Vagrantfile
The Vagrant VMWare Workstation plugin (for Windows) is compatible with Fusion images but you still have to specify `--provider=vmware_workstation`. However, the VVV Vagrantfile tries to load the default box in such case, so I added a conditional for the vmware_workstation provider so that it uses the Fusion box. 
Provisioned it, works without issues.
> Add support for VMWare Workstation

- config/phpmyadmin-config/config.inc.php
On VMWare, the default shared folder permissions are 777, which makes phpMyAdmin uncooperative, giving the following error message when trying to use it:
```
Wrong permissions on configuration file, should not be world writable!
```
This patch will disable permission checking in phpMyAdmin to get around this. The permission checking is a mechanism to avoid security issues on shared hosts, but since VVV is presumed to be a development environment this should cause no issues.
> Fix phpMyAdmin permission issue on VMWare

- .gitignore
- config/phpmyadmin-config/config.inc.php
- provision/provision.sh
If `config.inc.custom.php` exists in the `www/default/database-admin/` directory alongside the default `config.inc.php` file, it will be included so that our default configuration for phpMyAdmin can be overridden.
Props @grantnorwood for the initial approach in #588.
> [PR] Allow for a custom phpMyAdmin configuration file

- config/phpmyadmin-config/config.inc.php
We now provide a custom config file for phpMyAdmin and should
use that as a way to override settings such as this for other
providers. This is specifically a concern due to possible
security issues on public networks.
This reverts commit b18ca1347453da386733192930497b2c6f286218.
See #657 for conversation.
> [PR] Revert "Fix phpMyAdmin permission issue on VMWare"

- config/wp-cli/local.php
- config/wp-cli/quiet.php
- wp-cli.yml
Closes #563 
This defines a custom `wp-cli.yml` for external use on the host machine. 
If you have `wp-cli` installed locally and wanted to use it there instead of through vagrant ssh or other methods this should do it. 
It accomplishes this by requiring a few php files to silence uneccessary warnings and to redefine the database for connecting from outside the VM. 
So far in all local testing it has worked great.
> wp-cli support for local machine

- config/php5-fpm-config/xdebug.ini
By being more explicit about the defaults currently configured for
XDebug, we can make it easier to submit future pull requests for
changes as only the values of individual configurations will be
changed.
> [PR] Be explicit about defaults in XDebug configuration

- .gitignore
- provision/provision.sh
Just create a simple text file named `provision/github.token` with only your gh token to automatically set the token for composer
> set your GitHub token easily for Composer

- config/nginx-config/nginx.conf
- config/nginx-config/sites/default.conf
- config/php5-fpm-config/php-custom.ini
This allows sites in development to support more reasonable upload sizes for 2015. It also allows larger SQL (or .gz) files to be uploaded directly through the phpMyAdmin interface for those who do not use the command line.
See #454, #273.
Fixes #599.
> [PR] Bump max upload size to 1024M in PHP and Nginx

- Vagrantfile
This allows you to have multiple VVV instances (with different IP addresses) without name collisions and makes things slightly easier to identify in VirtualBox.
Fixes #512.
> [PR] Set the box name in VirtualBox to that of the working directory

- README.md
I just can't stop building tools for VVV.
This is [vvv-provision-flipper](https://github.com/bradp/vvv-provision-flipper); the handy, helpful for toggling between provisioning scripts.
:gift_heart:
> Add a link to vvv-provision-filpper in README

- Vagrantfile
Though the SMB config is wrapped in a conditional statement, Vagrant's built-in Ruby interpreter seems to be ignoring scope here. Using `config` in the scope shouldn't be an issue, but apparently is. Instead we'll use the explicitly-scoped `override` version to make sure nothing bubbles out unexpectedly.
Fixes #758
> Fix the HyperV Provider

- provision/provision.sh
The original Webgrind repository does not show full function names
when viewing cachegrind output. This fork resolves the issue.
Fixes #760.
> [PR] Update Webgrind repository to forked version supporting Xdebug 2.3

- Vagrantfile
This is ostensibly an improvement for hyperv providers, but carries extra benefits for all providers.
Hyper-V does not know how to make private networks, so the extra IP address configured by VVV is not needed (and when used with vagrant ghost, results in duplicate hosts entries that point to a dud address). This unsets the private network for the hyperv provider.
Additionally, this makes it much easier and more forwards-compatible to modify the VM ip address. Currently, if you need to change the vm's network (e.g. because your network is using the 192.168.50.* subnet), you must edit `Vagrantfile` directly. With an id for the network config, the ip can be overridden in the `Customfile` in one line:
```rb
config.vm.network :private_network, id: "vvv_primary", ip: "10.10.10.10"
```
> Simplify private network overrides

- config/bash_profile
Otherwise, test install scripts will default to using WordPress latest, which is incompatible with WP trunk tests.
From https://github.com/wp-cli/wp-cli/issues/2129#issuecomment-154356360
> Set the WP_CORE_DIR path so phpunit tests are run against WP trunk

- provision/provision.sh
The latest version is actually 5.1.x, but it requires PHP 5.6+. Updating to 4.8.x at least gets us to a version that has [available documentation](https://phpunit.de/manual/4.8/en/index.html).
I ran the WordPress test suite with this update and it still completes successfully. I'm not sure what other testing needs to be done to vet this change.
> Update phpunit to 4.8.x

- .gitignore
- Vagrantfile
- config/homebin/vagrant_up
Hi! This PR implements what was discussed in #778.
I've also added a custom trigger before reload that execute `vagrant_halt` script and after reload that execute `vagrant_up` script. Please let me know if a custom `vagrant_reload_before` and `vagrant_reload_after` might be more adequate for this kind of situation.
> Running custom scripts on vagrant up and reload

- Vagrantfile
- use `parallels.customize ["set", :id, "--longer-battery-life", "off"]` in its place
> update deprecated `parallels.optimize_power_consumption = false`

- config/nginx-config/sites/default.conf
- config/php5-fpm-config/www.conf
- www/default/index.php
The PHP FPM status page lists active requests, this is useful to debug running wp-crons.
Few people might use it, its requires only these few changes.
I'm using it to track concurrent cronjob workers that re-spawn themselves to process big data in background.
> Adding PHP FPM status page

- provision/provision.sh
This allows for `vvv-nginx.conf` to be located in a project's subdirectory, like the `private` directory on Pantheon:
```conf
server {
listen       80;
listen       443 ssl;
server_name  vvv.pantheon.example.com
root         {vvv_path_to_folder}/..;
include      /etc/nginx/nginx-wp-common.conf;
}
```
> Resolve relative paths in vvv-nginx.conf since not allowed by Nginx

- provision/provision.sh
use apt-cache policy instead of dpkg -s to check if pkg is NOT installed
sometimes dpkg -s will find Version information for packages that have
been removed, resulting in a false positive
1. If we check that a package exists and get a false positive, that package will never get installed.
1. If we check that a package doesn't exist and get a false positive, apt-get will attempt to install it and notice that it is already installed.
```bash
sudo apt-get remove virtualbox-5.0
dpkg -s virtualbox-5.0 2>&1 | grep 'Version:'
```
This results in a false positive due to 'Version:' being found in several places.
```bash
Version: 5.0.14-105127~Ubuntu~trusty
Config-Version: 5.0.14-105127~Ubuntu~trusty
Python-Version: 2.7
```
```bash
apt-cache policy virtualbox-5.0
```
The result is not a false …
> possible false positive in package_check

- config/wordpress-config/wp-tests-config.php
Based on our conversation here: https://twitter.com/jeremyfelt/status/707751217187819521
With this in place, you'd be able to `brew install mysql`, create the `wordpress_unit_tests` database:
```sql
CREATE DATABASE IF NOT EXISTS wordpress_unit_tests CHARACTER SET utf8;
```
And then add the following lines to your host machine's `.bash_profile`:
```php
export WP_TESTS_DB_HOST=localhost
export WP_TESTS_DB_NAME=wordpress_unit_tests
export WP_TESTS_DB_USER=root
export WP_TESTS_DB_PASSWORD=''
```
Assuming you also have PHPUnit installed (`brew install phpunit`), you show now be able to run `phpunit` from a terminal on the host machine and execute the unit tests as fast as possible.
> Allow unit test DB config to be supplied via environment vars

- provision/provision.sh
The version of Xdebug 2.4.0 that is available for our Ubuntu installation is not compatible with PHP 7.0. We instead retrieve the source package and go through the manual installation steps.
🎉
> [PR] Install Xdebug for PHP7

- provision/provision.sh
The SOAP module may be common enough to be part of the default install?
> Add php7.0-soap

- provision/provision.sh
- make code more standard and readable
- insert space around code inside $(( ... ))
- define variables within functions as local
Shell is special, even variables declared inside a function and inside
another block, appearing to have limited scope, will still be available
after the function call. Define as local to avoid potential issues.
> fix some ShellCheck code linter warnings

- config/homebin/db_restore
`db_restore` maps to `/srv/database/import-sql.sh` so no duplicate code here, however adding the command to the homebin makes it more easily accessible when doing manual backup/restore, outside of `vagrant halt` or `vagrant provision` (while vagrant is already up and running).
> Add db_restore command in homebin so one-off restores can be done

- Vagrantfile
Problem: Working on a **provision-post.sh** script, every time you want to test it, you have to run _all_ the provisioners.
Solution: Use the `--provision-with` switch to specify which provisioner(s) to run. Per the Vagrant [documentation](https://docs.vagrantup.com/v2/cli/provision.html):
> `--provision-with x,y,z` - This will only run the given provisioners. For example, if you have a `:shell` and `:chef_solo` provisioner and run `vagrant provision --provision-with shell`, only the shell provisioner will be run.
Since all of VVV's provisioners are `:shell`, this doesn't help much. However, if each one is named, you can do something like this: `vagrant provision --provision-with post`
> Provisioner names

- README.md
As per the discussion in issue #800, some people find it useful to use the `vagrant-vbguest` plugin for Vagrant to keep VirtualBox Guest Additions versions synchronized between the host and guest. Doing so can sometimes prevent subtle shared folder errors and doesn't seem to interfere with VVV's own operation.
This commit adds that plugin as a recommended installation step to the README. This commit also groups the three recommended plugins into a single logical step called "Optionally, install some convenient Vagrant plugins." Prior to this commit, each plugin was listed as its own step in the "first `vagrant up`" section of the README.
> Add vagrant-vbguest plugins recommendation to the README, group optional plugin steps

- config/mysql-config/my.cnf
query_cache_* entries should be under [mysqld] not under [mysql]. the current way is throwing errors on provision
> query_cache_* entries should be under [mysqld]

- config/memcached-config/memcached.conf
If you have PHP installed on your host machine, it is possible to [run WP-CLI on your host machine](https://blog.handbuilt.co/2016/05/18/how-to-use-wp-cli-without-ssh-access-to-the-server/#comment-287) or [run PHPUnit](https://make.xwp.co/2016/03/10/running-phpunit-tests-outside-vvv/) (see #785 and #739) for a site located in VVV by putting this into your `wp-config.php`:
```php
if ( file_exists( '/vagrant' ) ) {
define( 'DB_HOST', 'localhost' );
} else {
define( 'DB_HOST', '192.168.50.4' );
}
```
This works, but if you have a persistent object cache installed, it will break. If Memcached is installed on the host machine (e.g. `brew install memcached && brew install php56-memcache`), then you should also be able to connect to the Memcached instance running in Vagrant just like you can …
> Allow external connections to Memcached from host machine

- .gitignore
Following #863 the folder `config/nvm/` was showing as "Untracked files" by Git
> `.gitignore`: Ignore the nvm git clone in the 'nvm' directory in config

- provision/provision.sh
These are currently being installed with the common packages automatically, but have been missing in the past.
This also reorders the current list of extensions for readability.
Fixes #893.
> [PR] Add explicit support for php7.0-xml and php7.0-json packages

- provision/provision.sh
`wp core upgrade` would work just fine as an alias, but the correct
command is `wp core update`
Fixes #675.
> [PR] Use wp core update, not upgrade

- provision/provision.sh
The installation of local npm packages was running into trouble
due to what is likely a race condition caused by slow shared drives
between the host and guest machines. This is mostly a guess, but
seems plausible.
We can instead handle the initial SVN checkout, the npm package
installation, and the initial build via grunt in the VM's `/tmp`
machine. Once this is all prepped, it is then moved to the final
location in `/srv/www/wordpress-develop` before other scripts that
install WordPress run.
Anything involving files runs quite a bit quicker during the initial
setup. The move of the directory takes a long while though, which
kind of negates the original speed. :)
But speed isn't the problem, incomplete local npm packages is.
Fixes #825.
> [PR] Checkout and initialize wordpress-develop in /tmp/

- .gitignore
- README.md
- config/nginx-config/sites/default.conf
- config/nginx-config/sites/deprecated.conf
- database/init.sql
- provision/provision.sh
- www/default/index.php
This has been around since the beginning of VVV, when the develop
repos had not yet been created. There's not much sense in providing
both the legacy trunk repo and the modern develop repo.
We'll still want to document the best way to continue using the
wordpress-trunk directory if it exists in your VVV instance.
See #921.
> [PR] Remove WordPress trunk from default provisioning

- config/homebin/xdebug_on
By default, the xdebug log file is owner writeable (www-data). When
the vagrant user runs PHP inside the VM, say for `wp`, while xdebug
is enabled, it needs access to the file as well.
We made vagrant part of the www-data group in #705, and moved the
log file to a more accessible location, but it was still not
writeable.
Fixes #621.
> [PR] Ensure the log file for xdebug is group writeable

- provision/provision.sh
If xdebug is enabled when composer runs, it will display warnings
and may result in slow provisioning. We should be able to assume
that xdebug is off during provisoning and remains off until enabled
again after provisioning.
Fixes #919.
> [PR] Disable xdebug early in provisioning

- provision/provision.sh
PHPUnit 5.6 is the current stable release series.
It became stable on October 7, 2016.
It's also the only version officially supported by php7+ 
`PHPUnit 4.8 is supported on PHP 5.3, PHP 5.4, PHP 5.5, and PHP 5.6.`
> Update to phpunit to major version 5

- config/apt-source-append.list
On October 18th, with the release of Node.js 6.9.0, the 6.x branch was moved to LTS status. Seems like now is a good time to update our default version.
> Switch to the Node.js 6.x LTS release

- Vagrantfile
This restores access to the dashboard by explicitly adding it do the domain array in the Vagrantfile.
> Allow vvv.dev access in feature/split-provisioners.

- provision/provision.sh
I noticed that WP-CLI wasn't updating successfully on `vagrant provision` and noticed the error `Cannot pull with rebase: You have unstaged changes.` so I dug around in the provision file and found that after pulling the latest WP-CLI version `composer update` runs.
This command does install dependencies but also updates them to the latest version, writing `composer.lock` in the process and makes it impossible to pull a new version from GitHub. 
This is easily solved by running `composer install` instead which is the proper way to install dependencies.
Ping @jeremyfelt
> WP-CLI: Use composer install instead of update

- .gitignore
- Vagrantfile
This commit adds support for a `vvv-custom.yml` file and, if it exists, completely overrides the `vvv-config.yml` files.
In my opinion, if a user is adding a custom config, she/he should have complete control over all configuration and not a merged configuration with the default.
Resolves #1045
> Add support for custom YAML config file.

- provision/provision.sh
Google.com redirects to a local server like Google.co.in based on geolocation. Without recursion the wget call does not detect such redirects. That further results in major provisioning errors since the `network_check` call happens at multiple stages.
This PR follows such redirects upto 2 levels. I've tested provision over mobile networks with and without this PR. Network connection detection is much more reliable with this recursion flag enabled.
> Improves Network Connection Detection

- Vagrantfile
- vvv-config.yml
Allow a hosts key to yo be added to a site in vvv-config.yml
This is fully compatible with existing vvv-hosts files.
```
wordpress-default:
repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
vm_dir: '/srv/www/wordpress-default-provisioner'
hosts:
- local.wordpress.dev
wordpress-develop:
repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
vm_dir: '/srv/www/wordpress-develop-provisioner'
hosts:
- src.wordpress-develop.dev
- build.wordpress-develop.dev
```
> Support hosts in vvv-config.yml

- Vagrantfile
- config/homebin/xdebug_off
- config/homebin/xdebug_on
- config/nginx-config/nginx-wp-common.conf
- config/nginx-config/nginx.conf
- config/nginx-config/php7.0-upstream.conf
- config/php-config/php7.0-custom.ini
- config/php-config/php7.0-fpm.conf
- config/php-config/php7.0-www.conf
- config/php-config/xdebug.ini
- provision/provision-site.sh
- provision/provision.sh
This adds an additional optional variable of `upstream` to vvv-config.yml to allow you to set the nginx upstream. 
It also switches xDebug from source to the PPA as this is compatible with multiole PHP versions.
An example config for testing:
```
---
sites:
wordpress-default:
repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
vm_dir: '/srv/www/wordpress-default-provisioner'
upstream: php71
hosts:
- local.wordpress.dev
wordpress-develop:
repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
vm_dir: '/srv/www/wordpress-develop-provisioner'
upstream: php56
hosts:
- src.wordpress-develop.dev
- build.wordpress-develop.dev
wordpress-trunk:
repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-trunk.git
vm_dir: …
```
> Support multiple php versions through vvv-config.yml & utilities

- .gitignore
- config/bash_profile
- provision/provision.sh
Previously, VVV was cloning the wp-cli repo and installing
composer dependencies. This switches to the standard wp-cli
installation method which will make updating wp-cli easier.
`wp cli update` will run on re-provision.
Users can run `wp cli update` at any time
or `wp cli update --nightly` to update to the latest nightly.
Fixes #983.
> Change wp-cli to standard installation

- README.md
- Vagrantfile
- config/mysql-config/my.cnf
- config/mysql-config/root-my.cnf
- database/import-sql.sh
- provision/provision.sh
This is the first step in #876 and #949. Switching to MariaDB available
in the official Ubuntu 14.04 repositories is a very safe change and
it paves way to easily upgrade to 10.0 or 10.1 in a later step.
> Switch from MySQL 5.5 to MariaDB 5.5

- config/nginx-config/nginx-wp-common.conf
- config/nginx-config/sites/default.conf
Before `$args` are passed to the URL, `$is_args` will add a `?` if
args are detected and nothing if args are not.
Not having this in place can cause some strange issues with ignored
query params. See
http://v2.wp-api.org/guide/problems/#query-parameters-are-ignored
Fixes #1062.
> [PR] Include `$is_args` in nginx `try_files`

- provision/provision.sh
This appears to be in better shape for PHP7 than php7.0-memcache
and provides php5.5-memcached, php5.6-memcached, php7.0-memcached,
and php7.1-memcached.
Fixes #1067.
> [PR] Add the php-memcached package to default provisioning

- config/subversion-config
- provision/provision.sh
This adds a `config` file for the `vagrant` user and defines
`colordiff` as the diff command to use when running `svn diff`
from within the VM.
Fixes #908.
> [PR] Set colordiff as the default svn diff cmd-tool

- provision/provision-site.sh
- provision/provision.sh
The new `vvv-config.yml`/`vvv-custom.yml` allows you to specify a site or sites, with various keys. However, a `vvv-init.sh` may want to specify custom keys that are too specific to apply to all VVV sites.
This PR installs `python-pip` and the `shyaml` dependency, and adds a bash function named `customvalue` for retrieving those keys. When the `custom` section or the requested key are not defined or found, the function will return nothing
E.g. in `vvv-init.sh`
```
colour=`customvalue 'colour' 'pink'`
echo "Hello there :) This site is a ${colour} site"
```
Which when ran will print `Hello there :) This site is a pink site`, and can be changed as follows in `vvv-custom.yml`:
```
redsite:
custom:
colour: red
```
Resulting in `Hello there :) This site is a red site`
Nested keys can be …
> Custom keys for custom provisioning in vvv-init.sh

- config/bash_profile
After the modifications associated with #1068, PHPUnit tests files and WordPress source code in wordpress-develop site are no longer in `/srv/www/wordpress-develop/tests/phpunit/` and `/srv/www/wordpress-develop/src/`. They were moved to `/srv/www/wordpress-develop/public_html/tests/phpunit/` and `/srv/www/wordpress-develop/public_html/src`, respectively.
The modifications in this PR simply update the `config/bash_profile` file with the new paths.
> Update WP_{TESTS|CORE}_DIR to match changes in #1068

- provision/provision-site.sh
If a site is flagged to skip provisioning, VVV still handles its hosts and custom config values. Instead, it should 'skip provisioning' these
> Skip provisioning of skipped provisioned sites

- provision/provision.sh
In #420, we added a line to provisioning that attempts to set "ipv4" as the only allowed protocol for postfix due to issues in how network connections managed the ipv6 connection.
Because the config file does not yet exist during initial provisioning, that caused an error message saying as much. See #628.
It turns out that this line hasn't been doing anything. :)
I first went down the path of using `debconf-set-selections` to set the protocol value. This works, but then disables ipv6 entirely as a valid protocol. Since we haven't heard of any other issues
besides the original in #420, I think it's safe to not make any change here and then watch for any problems.
I have a feeling that postfix has gotten better about this. In the documentation for the `inet_protocols` config, it's mentioned …
> Remove attempt to enforce ipv4 in postfix

- README.md
- config/apt-source-append.list
- provision/provision.sh
This makes the upgrade from MariaDB 5.5 to 10.1, the current stable release.
I first looked at using the [ondrej repo](https://launchpad.net/~ondrej/+archive/ubuntu/mariadb-10.0), mentioned by @LoreleiAurora in #876, but that repo has been deprecated.
Instead, the [official MariaDB repositories](https://downloads.mariadb.org/mariadb/repositories/) provide a nice guide to finding the proper packages for Ubuntu 14.04 and seem to be working fine after a fresh provision.
The upgrade from MariaDB 5.5 to 10.1 on an existing VM involves a few steps. We should get this into 2.0.0 so that fresh provisions already have the latest.
See #949.
Fixes #876.
> Install MariaDB 10.1 in default provisioning

- provision/provision.sh
The command we use to check if a package is installed, `dpkg -s`, does not appear to properly follow alias names. After initial provision, `dpkg` fails to see that several packages are already installed and then falsely flags them to be installed.
Output during a provisioning looked like this:
```
==> default:  * php7.0-dev                                          7.0.16-4+deb.sury.org~trusty+1
==> default:  * php-pear                                            1:1.10.1+submodules+notgz-8+donate.sury.org~trusty+2
==> default:  * php7.0-imagick [not installed]
==> default:  * php7.0-memcache [not installed]
==> default:  * php7.0-memcached [not installed]
==> default:  * php7.0-bcmath                                       7.0.16-4+deb.sury.org~trusty+1
==> default:  * php7.0-curl …
```
> Use direct package names rather than alias names

- Vagrantfile
New vvv-config.yml keys.
```
vm_config:
memory: 1024
cores: 1
```
Fixes #1120
> Allow CPU & Memory to be configured.

- www/default/index.php
The fonts license require we mention it when using or bundling it. I've added a CSS comment before it's inclusion directing users to the license
Related to https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1122
> Source Code Pro License

- docs/en-US/governance.md
From http://oss-watch.ac.uk/resources/governancemodels:
> A governance model describes the roles that project participants can take on and the process for decision making within the project. In addition, it describes the ground rules for participation in the project and the processes for communicating and sharing within the project team and community. In other words it is the governance model that prevents an open source project from descending into chaos.
A governance model is a healthy thing for any open source project to have. For VVV, I'd like this to be a "[living reflection of the group's intentions](http://producingoss.com/en/written-rules.html)". 
This first draft is my attempt to describe the structure of the project from my perspective. Please feel free to suggest any changes or …
> Introduce governance documentation

- docs/en-US/contributing.md
This is making the build more confusing (likely my fault) in Travis,
so I'm going to remove it for now and work around it in another way.
> Remove symlink in docs to CONTRIBUTING.md

- .github/CONTRIBUTING.md
- CHANGELOG.md
- docs/en-US/adding-a-new-site/changing-php-version.md
- docs/en-US/adding-a-new-site/custom-domains-hosts.md
- docs/en-US/adding-a-new-site/custom-paths-and-folders.md
- docs/en-US/adding-a-new-site/index.md
- docs/en-US/adding-a-new-site/migrating-vvv1.md
- docs/en-US/adding-a-new-site/nginx-configs.md
- docs/en-US/adding-a-new-site/setup-script.md
- docs/en-US/basic-usage.md
- docs/en-US/built-in-wp-installs.md
- docs/en-US/default-credentials.md
- docs/en-US/governance.md
- docs/en-US/history.md
- docs/en-US/index.md
- docs/en-US/installation/index.md
- docs/en-US/installation/software-requirements.md
- docs/en-US/troubleshooting.md
- docs/en-US/vm_config.md
- docs/en-US/vvv-config.yml.md
- docs/en-US/what-is-vvv.md
We'll be using Jekyll in the near future, along with the docs repo at https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org.
This change makes it easier to manage permalinks, page titles, and templates.
> [PR] Add Jekyll template config to documentation

- docs/en-US/migrating-vvv1.md
The link in the migration page was incorrect.  See https://varyingvagrantvagrants.org/docs/en-US/migrate-vvv-1/. The link should point to https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/custom-paths-and-folders/, but points to https://varyingvagrantvagrants.org/docs/en-US/migrate-vvv-1/custom-paths-and-folders.md instead.
> Fix link to custom paths and folders docs

- docs/en-US/adding-a-new-site/custom-paths-and-folders.md
I tried to use a relative path for `vm_dir` but get the following error:
```
vm:
* The shared folder guest path must be absolute: www/patternlab/theme/public
```
So there should be absolute paths in the docs :)
> Use absolute vm_dir paths in custom-paths-and-folders.md

- Vagrantfile
The existing recursive blob causes massive slowdown of everything (provision, ssh etc) once I've got a few projects setup, especially if they have numerous directories.
This change limits the lookups to only look at the primary directory and a `provision` subfolder rather than unlimited depth. This matches what is documented, though other code such as provision-site.sh still looks [4 levels deep](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision-site.sh#L93).
On my setup doing `vagrant ssh` returns in seconds rather than potentially minutes. Should be useful in situations such as https://jjj.blog/2016/05/slow-vagrant/
Related: #595
> Speed up checking for `vvv-hosts` files

- provision/phpcs/composer.json
- provision/provision.sh
Relates to #922 
Introduce composer installation of phpcs and the sniffs for WP and keep it in the right place.
Removes 2 git operations per provision.
> provision phpcs + wp sniffs via composer

- provision/phpcs/composer.json
Tells composer to use the scripts folder for PHPCS, this ensures that new machines have the correct path, and old machines continue to work
> Force composer to use the scripts folder not the bin folder

- docs/en-US/references/default-credentials.md
Just fixing a link to the correct wiki page in the docs. :)
> fix link to SQL wiki page in docs

- provision/provision.sh
`vagrant up` installs rvm with a current ruby and then installs mailcatcher
Due to an [upstream bug in rvm](https://github.com/rvm/rvm/issues/4068) (or better the installer) the installation of rvm somewhat fails, skipping the ruby installation, which then leads to mailcatcher failing to install with symptoms similar to #985
[This line](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/ed7bee10d29b989d05c7ce8203af1dd8e42f4cc1/provision/provision.sh#L518)
curl --silent -L "https://get.rvm.io" | sudo bash -s stable --ruby
could be replaced by
curl --silent -L "https://raw.githubusercontent.com/rvm/rvm/stable/binscripts/rvm-installer" | sudo bash -s stable --ruby
The reasoning for this is that `https://get.rvm.io` points to the `master` branch of rvm which might not play along with the …
> rvm (and hence mailcatcher) installation broken (upstream bug)

- README.md
The [installation instructions](https://varyingvagrantvagrants.org/docs/en-US/installation/) are nice.
However, it takes 3 clicks to get there, and it took me a bit to figure out the first click:
- https://github.com/Varying-Vagrant-Vagrants/VVV#how-to-use-varying-vagrant-vagrants - click the link to the website
- click the "documentation" link under the "Documentation" section
- click "Installing VVV 2"
I would also make a similar change to the front page of https://varyingvagrantvagrants.org/ but I don't see how to do it.
> Add direct link to installation instructions from README

- provision/provision.sh
This PR aims to improve the log output from `vagrant up`.
- Provisioner script: Remove apostrophes in comments that break `vim` syntax highlighting
- Add "Installing/updating npm" and "npm-check-updates" messages during install
Output before this change includes a bunch of extra stuff:
```
==> default: Loading composer repositories with package information
==> default: Updating dependencies (including require-dev)
==> default: Package operations: 29 installs, 0 updates, 0 removals
==> default:   - Installing d11wtq/boris (v1.0.8): 
==> default: Downloading (connecting...)
==> default: 
==> default: Downloading (0%)
==> default:            
==> default: 
==> default: 
==> default: Downloading (20%)
==> default: 
==> default: Downloading (40%)
==> default: 
==> default: Downloading (60%) …
```
> Cosmetic improvements to install process

- provision/provision.sh
Fixes #1212 and in the process significantly improves the runtime and performance of `vagrant up` (a fresh install now runs about 10-15 minutes faster for me).
Removing the `&> /dev/null` from `npm install grunt-sass` reveals a pretty nasty issue.  It starts like this:
```
==> default: > node-sass@4.5.3 install /usr/lib/node_modules/grunt-sass/node_modules/node-sass
==> default: > node scripts/install.js
==> default: Unable to save binary /usr/lib/node_modules/grunt-sass/node_modules/node-sass/vendor/l$
nux-x64-48 : { Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/grunt-sass/node_modul$
s/node-sass/vendor'
==> default:     at Error (native)
==> default:     at Object.fs.mkdirSync (fs.js:923:18)
==> default:     at sync …
```
> Fix errors and slowness during grunt-sass install process

- provision/provision.sh
> Fix wrong path for phpcs and phpcbf executables.

- provision/phpcs/composer.json
WordPress Coding Standards are, currently, installed/updated to the wrong directory. Rather than being added to `/srv/www/phpcs/CodeSniffer/Standards/WordPress` as expected, the standards are being installed in `/vargrant/provision/phpcs/vendor`. I tracked the issue down to this comment, https://github.com/oomphinc/composer-installers-extender/issues/6#issuecomment-303054875.
Basically, we just need to make sure that `oomphinc/composer-installers-extender` knows that it should be working with dependencies of the type, `phpcodesniffer-standard`.
> PHPCS composer.json needs `phpcodesniffer-standard`

- provision/phpcs/composer.json
- provision/provision.sh
Adds the minimum VIP coding standards ruleset used to check deploys and review automation at WordPress.com VIP.
This ruleset doesn't replace the one in the main WP coding standards, it's the bare minimum intended to flag anything serious with only the things that are absolutely essential, while letting VIP iterate faster
> Adds PHPCS WP.com VIP Minimum Coding Standards Ruleset

- provision/provision-site.sh
This adds a variable using the `get_hosts` function in `provision-site.sh` that allows the variable `vvv-hosts` to be used in vvv-nginx.conf so the user doesn't need to manually specify the hostnames in both vvv-custom.yml and vvv-nginx.conf.
> Add variable to provision-site.sh for NGINX's server_name

- Vagrantfile
- config/nginx-config/sites/default.conf
- provision/provision.sh
- vvv-config.yml
- www/default/index.php
- www/default/style.css
Adds support for `vvv.local` `vvv.test` and `vvv.localhost`, and changes prompts to recommend `vvv.test`
This goes some of the way towards correcting https://github.com/Varying-Vagrant-Vagrants/VVV/issues/583 though it doesn't impact the default sites
> Alternate Dashboard domains

- provision/provision.sh
Adds `--no-progress` and `--no-interraction` arguments for composer `update` and `self-update` commands:
`--no-progress`: Do not output download progress.
`--no-interaction`: Do not ask any interactive question.
Previously logs would look like this:
```
==> default:   - Installing mockery/mockery (0.9.9):
==> default: Downloading (connecting...)
==> default:
==> default: Downloading (0%)
==> default:
==> default:
==> default:
==> default: Downloading (5%)
==> default:
==> default: Downloading (10%)
==> default:
==> default: Downloading (15%)
==> default:
==> default: Downloading (20%)
==> default:
==> default: Downloading (25%)
==> default:
==> default: Downloading (30%)
==> default:
==> default: Downloading (35%)
==> default:
==> default: Downloading (40%)
==> default:
==> default: …
```
> Fix composer polluting logs with progress

- Vagrantfile
Right now the splash indicates 2.0.0 for both `master` and `develop`, which isn't accurate.
Instead, lets bump `develop` to 2.1.0, indicating 2.1 is in development, and add the git branch to the splash. This PR does that:
When we release 2.1, we can bump the version in `develop` to 2.2 or 2.1.1, without needing to do the faff of updating the version number on release
> Branch & 2.1 in Splash

- config/nginx-config/nginx.conf
- provision/provision.sh
This will automatically refresh the cert used for domains by default by appending a version number to the server.crt and server.key files.
Pretty sure this cert is half broken anyway, but it at least aligns with where we're currently at. 🙈
> Generate a new certificate and private key including .test domains

- provision/provision.sh
#1306 was accidentally merged into the master branch rather than develop.
Fix composer polluting logs with progress
Adds `--no-progress` and `--no-interraction` arguments for composer `update` and `self-update` commands:
`--no-progress`: Do not output download progress.
`--no-interaction`: Do not ask any interactive question.
> Merge change in master from #1306

- provision/provision.sh
This allows to add additional memcached configs which will automatically be started by the default memcached service.
Fixes #1327.
> Support multiple memcached servers by adding `/etc/memcached_default.conf`

- Vagrantfile
cleans up the splash with Heredocs, colour variables, and compacts the ASCII art down to 3 lines. Also adds some nice coloured stars to fix visual balance
I'm going to recommend this be merged into 2.2 once 2.1 is released
before:
after:
> Tighter Splash

- Vagrantfile
Bumps the develop version to 2.2 so that it's clearer when people say 2.1 if they mean stable or not
also saves some time when it comes to release
> Bump version number on develop so it doesn't get confused with master

- .gitignore
Noticed this because I'm using `status.showUntrackedFiles = all`, see https://git-scm.com/docs/git-config#git-config-statusshowUntrackedFiles.
```
➜  vagrant-local git:(develop) ✗ git status -u .
On branch develop
Your branch is up to date with 'origin/develop'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
config/nvm/
nothing added to commit but untracked files present (use "git add" to track)
```
> Ignore the whole /config/nvm/ directory

- Vagrantfile
- provision/provision-utility-source.sh
This adds support for custom git branches for utility sources, same as we do for sites. For back-compat the default branch will be `master`.
I also added a check whether there is already a `core` utility before adding the default repo. This is to support a custom branch/repo for `core` as well.
Example config:
```yml
utility-sources:
fancy:
repo: https://github.com/fancy/fancy-utilities.git
branch: master
solr: https://github.com/ocean90/vvv-solr-utilities.git
core:
repo: https://github.com/ocean90/vvv-utilities.git
branch: my-new-feature
```
> Add support for custom git branches for utility sources

- provision/provision.sh
This is more in line with the version Travis CI uses when running WordPress core unit tests.
Fixes #1353
> [PR] Update PHPUnit to 6.x

- Vagrantfile
Bumps up the default memory allocation from 1024 to 2048 in the vagrant file
Fixes https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1366
> 1024mb -> 2048mb VM RAM

- vvv-config.yml
Adds the vm_config section to the config file by default so users are aware of it, and bump up the memory from 1024 to 2048
Related to https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1366
> VM Config in vvv-config.yml

- .gitignore
At the moment, /config/nvm/ folder itself is prompted as unversioned file
> need to ignore the nvm directory itself as well

- vvv-config.yml
The custom site templates provisioner is more robust, we can make sure new users get it instead of the older default site template
> Swaps the git repo of the default site to the custom site template

- Vagrantfile
as the `netsensia/ubuntu-trusty64` box no longer exists.
Fixes #1399
> Update vagrant box used for VMWare Workstation and VMware Fusion

- Vagrantfile
- vvv-config.yml
- Provide the ability to specify the default provider to use for vvv without having to use the `--provider` parameter.
- In the rare case a user's existing network is using a `192.168.50.x` subnet, it can now be overridden in the config rather than the `Vagrantfile`. As it's a rare occurrence, it's not documented in the `vvv-config.yml` file.
> Add vm_config settings for the private network ip and vagrant provider

- provision/phpcs/composer.json
> switches the phpcs install to use github rather than vcs for the vip coding standards

- Vagrantfile
Also explicitly states that it's a git based install
This might fix #1471 by removing the bash conditional, which probably fails on Windows
> Makes the check for git vs zip in the splash a little more reliable

- vvv-config.yml
The current dev template only works for a single domain, this one is a modern replacement, we should use it by default for new users
> Changes the default core dev site to the new custom site template develop

- provision/provision.sh
runs composer as the vagrant user, and fixes the ownership of the com…poser cache folder.
Previous PRs didn't catch all uses or handle the ownership of the composer cache folder.
Additionally I merged the require commands into a single command which should improve provisioning times a little and reduce output spam
Closes #1320
> Run composer as the vagrant users

- provision/provision.sh
Without this, some PHP 7.2 packages don't get installed
> fixes the installation of a nonexistent package

- provision/provision.sh
Reverts Varying-Vagrant-Vagrants/VVV#1483
Seems this broke things for new users. We might force the TLS-CA utility on new users but that'll be a new thing, and it'll be built into VVV 3 anyway
> Revert "Removes the legacy TLS certificate generation"

- Vagrantfile
changes the vagrant file to always copy vvv-custom.yml if it doesn't exist, then alway use that file
closes #1356
> Autocopy vvv-config.yml to vvv-custom.yml

- Vagrantfile
In theory this should prevent vagrant destroy and halt from failing when a trigger error occurs
Helps make vagrant destroy more robust
> Sets onerror triggers

- provision/provision.sh
which is needed when building some ruby package dependencies, such as those mail catcher relies on
With this, mailcatcher builds, though I can't access it via the `http://vvv.test:1080` url
> adds the ruby-dev package

- provision/provision-site.sh
Most of those sites would have triggered the nginx service to restart despite me telling VVV to skip them. Ideally the vagrant file wouldn't even trigger the site provisioner for those sites, that would be a future step
> don't restart nginx if a site is set to skip provisioning

- config/bash_profile
Updated the bash profile script to provide a more pleasant default prompt:
Users can still override this by putting a `.bash_prompt` file in their homefolder
> adds a slightly nicer default prompt that adds colours

- Vagrantfile
This has multiple advantages:
- We controll the box
- Security updates from Jenkins weekly rebuilds
> Switch to vvv-base/ubuntu1404 for virtualbox

- Vagrantfile
If you set a site to skip provisioning, its provisioner still runs, but exits immediatley.
Instead, this PR adds the same check to the Vagrant file, speeding things up a little bit, and reducing provisioner output
> skips running a site provisioner if the site has been skipped in the config file

- provision/provision.sh
Swaps the network detection to use ppa.launchpad.net instead of google.com, fixes #1588 and might fix VVV use in China
> Use PPA Launchpad for network detection

- Vagrantfile
`:mount_options` for `"log/", "/var/log"` were introduced in https://github.com/Varying-Vagrant-Vagrants/VVV/commit/b132546927759ed34ca91d0b118f686acf16e6d8#diff-23b6f443c01ea2efcb4f36eedfea9089R343 but override to unset them for parallels provider was not added. This change adds this override.
Fixes #1600
> Added missing override for parallels shared folder

- config/bash_profile
Fix #1602 
Before:
After:
PS: the color of the RGB is might different since i'm using custom color scheme with iTerm2 on Mac
> fix bash prompt not wrapping correctly. 

- vvv-config.yml
> replaces the default wp dev site with a single URL to prevent confusion

- provision/provision.sh
Currently, Go is installed twice: through `apt` (where we get v1.2.1, which is too old for MailHog), and then through a tarball (where we get v1.10.3). This PR removes the `golang-go` package from the list and updates the tarball to v1.11. I could not find a way to avoid getting the source and tests, unfortunately—when I tried excluding them in the `tar` command, compiling MailHog failed.
In addition, nvm is currently installed by cloning the repository. This is the normal method, but it pulls in a host of unnecessary files, including test files whose names end in dots, which are a nuisance to deal with on Windows. This PR switches the `script` install method so that only the three files necessary are downloaded.
> Reduce nvm and Go footprint

- Vagrantfile
When vagrant up is run the first time, it makes a copy of vvv-config.yml to vvv-custom.yml and shows the a message (as shown in image 1). This message is confusing as it talks about the action of VVV and also has suggestion that users should use vvv-custom.yml.
This commit changes that message to be more clear (as shown in image 2) by separating the action of VVV and suggestion for the user in 2 different lines. The suggestion also has an explanation on why changes should be made on vvv-custom.yml instead of vvv-config.yml.
> Fix message shown when vvv-custom.yml is copied

- CHANGELOG.md
- Vagrantfile
Fixes #1663 by only provisioning a site if `skip_provisioning` is set to `false`
> only provision hosts for active sites

- Vagrantfile
2.1.3 is a known bad version, so 2.1.4 would be the minimum to avoid that
It increases the minimum vagrant version to v2.1.4
> Bump the vagrant minimum version

- CHANGELOG.md
- config/nginx-config/sites/default.conf
- provision/provision.sh
Allows the default nginx config to be extended
> Tomjn default nginx blocks folder

- Vagrantfile
These are the changes I made to my local vagrant file as described on https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1579.
Basically, this just allows you to create symlinks inside shared folders. This is handy, as described on the related ticket, so users on Windows host machines can replace their node_modules folders inside shared folders with a symlink, because npm, when ran from the guest OS, doesn't work well in folders shared with a windows host machine.
> allow symlinks

- vvv-config.yml
Removes the reference to .dev in the my-example-site comment that starts on line 44.
> [ UPDATE ] changed mention of .dev to .test

- provision/provision-network-functions.sh
- provision/provision.sh
This makes the main provisioner script a bit smaller, and puts them in a file that can be included, so that these functions are duplicated in other places, e.g. PHP provisioners
> moves the network provisioning functions into a separate file

- README.md
New installations of VVV will install Mailhog, not Mailcatcher. The project's README file should reflect this.
> Replace Mailcatcher with Mailhog in `README.md`.

- provision/provision-site.sh
Allow custom site provisioner update after a git push force
> Fix site provision update after forced update

- provision/provision.sh
Changes the git-lfs apt key check and adds the --force-yes parameter to the apt-get install
This should add the key for existing users not just fresh installs, though it's unlikely they'll see any difference as the packagecloud issue doesn't impact them
> Apt-get adjustments

- Vagrantfile
- provision/provision.sh
Currently MailHog and MHSendmail are built from source, requiring the golang runtime
This removes the golang dependency and downloads the MHSendmail and MailHog built binaries from GitHub instead, which should improve reliability and speed up provisioning.
It also makes a handful of other tweaks to make things a little more verbose, and fixes a sourcing bug
> built mailhog

- CHANGELOG.md
- config/homebin/db_backup
- database/import-sql.sh
- provision/phpcs/composer.json
- vvv-config.yml
Database backups take a long time for some people, so this provides an easier method of disabling them.
It also makes a handful of other tweaks, updating the `vvv-config.yaml` and changelog to surface the changes, a slightly more verbose backup script, and a tweak to the VIP Coding standard PHPCS inclusion
> Optional db backups

- CHANGELOG.md
- provision/provision-site.sh
Previous commits have broken the WordPress-Meta-Environment (seemingly introduced in b13c455f). Reference to a variable that doesn't exist needs to be renamed to the correct variable name.
Fixes WordPress/meta-environment#122
> Update provision/provision-site.sh to fix WordPress Meta Environment

- CHANGELOG.md
- Vagrantfile
- provision/provision-site.sh
This attempts to optimise site provisioning by doing several things:
- Adds the `{vvv_tls_cert}` and `{vvv_tls_key}` so that site provisioners don't have to always copy paste the same chunk of code in their provisioners
- Optimise the `vvv-hosts` part so that it doesn't look for them if their are hosts in the config, and so that it then checks common places first
- Massively bumps up the number of warnings and error messages that could be shown for cases when things go wrong that weren't handled previously
- Moves hosts file parsing into its own function
- Simplified skip provision by returning early so that half the file can be moved over 1 indent for easier reading
> Site provisioner optimisations and TLS keys

- CHANGELOG.md
- Vagrantfile
- provision/provision.sh
Related to https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/18 and @Mte90, this adds the `tideways.vvv.test` domain when a utility named tideways is active.
This means that the utility PR will need to:
- Update the TLS CA to make sure a certificate for this domain gets generated
- Update its nginx configuration to the new subdomain
Once this is done and merged in, we'll update the `vvv-config.yml` in the following release ( `2.5.2`? `2.6`? ) and advertise that it's available for testing
> Support the Tideways subdomain addition to hosts

- CHANGELOG.md
- Vagrantfile
- config/homebin/vagrant_up
Restart nginx in a trigger rather than a provisioner so that when a contributor day user uses `vagrant up --no-provision` it doesn't break things
> Fixes #1669

- Vagrantfile
This fixes the tideways check in the utility section by moving the hostsupdater check to later in the vagrant file
> Move the hostsupdater usage to later in the vagrant file

- config/bash_profile
This PR updates the `WP_CORE_DIR` and `WP_TESTS_DIR` variables after the changes made in vvv-config.yml (commit 67c4945ef23f5dfd544cb67f6bdf2e7df90fdf15)
The directory for the development installation changed from `/wordpress-develop` to `/wordpress-trunk`
> Update WP_CORE_DIR and WP_TESTS_DIR after changes in vvv-config.yml

- CHANGELOG.md
- Vagrantfile
https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1654
> Fix #1654, auto install vagrant plugin

- vvv-config.yml
Skip the develop and the meta environment using skip_provisioning instead of commenting it out
Provisioning for new users the first time should be as fast as possible, but enabling these templates should be easy
> Disable the trunk develop site by default

- CHANGELOG.md
- Vagrantfile
closes #1750
rearranges the splash a little to fit in the install path, and puts v's before the version numbers. I moved the VBox version up onto the same line as the vagrant version so it occupies the same space
Before:
After:
> Put the path in the splash screen

- CHANGELOG.md
- Vagrantfile
- vvv-config.yml
Contributor day setup no longer has to use `sed` to swap the vagrant box, it can be configured via the config file now. This also means users who want to switch away from that box now have an easy path to do so, change the flag to `false` and reprovision
> contributor box flag

- CHANGELOG.md
- Vagrantfile
- config/homebin/vagrant_provision
- config/homebin/vagrant_up
closes #1752
Sometimes users aren't sure if things finished succesfully, and the end of a provision just looks like more output that abruptly stopped. We tried adding a short message but I don't believe it's enough, so I put much more in:
I did encounter an issue where `vagrant_provision` couldn't be ran by vagrant with a permission denied error, I'm unsure why though as I've only modified the contents of the file in an existing instance, and `vagrant_up` worked fine
> Post-up/Provision splash

- CHANGELOG.md
- Vagrantfile
adds a virtualbox_path function to the vagrant file to help locate virtualbox on Windows
This tries to close #1753 by replacing the naive check for VBoxManage with the one Vagrant itself uses so that it works better on Windows. Currently it only works in Windows if `VBoxManage` is in `PATH` which isn't true for most users
Still needs testing on Windows to confirm it does what it says, but I can confirm nothing is changed under MacOS
> Try to fix WIndows VBox version ???

- CHANGELOG.md
- Vagrantfile
We've been pushing people to `vvv.test` for a while, it's time we acted on our deprecations and streamlined. Decisions not options right? This way it's less confusing for new users where the dashboard lives
related to some discussion in #1762 that revealed potential sources of confusion for users
As an aside, it looks like `http://vvv` is possible and it gets added to the hosts file, but VVV doesn't do this itself. I  believe the hostsupdater plugin is doing this. I don't know how to remove it at the moment but I'd like to if possible
> removed 3 dashboard domains in favour of vvv.test

- CHANGELOG.md
- provision/provision-site.sh
It adjusts the site provisioner script so that if the `git clone` fails, it aborts and tells the user. It also adjusts the other messages, and simplifies the logic at the end of the script
> Abort if git clone fails, and improve messaging

- provision/provision-site.sh
Updates the site provisioning script to use `service xxx reload`, which isn't subject to the burst limits `service xxx restart` is.
Issue: #1780
> issue/1780 – Reload vs restart nginx to avoid service burst limits during site provisions

- README.md
A lot of the readme is redundant, mentioned on our site, or provided by github itself ( e.g. the contributor page and the license )
> dramatically simplify the readme

- Vagrantfile
reference the version and config files to copy into the VM using absolute paths
This fixes copying those files when you provision in a subfolder
> Fix a file copy provisioner bug

- provision/provision.sh
This silences the composer root warning issue for now, note that with `noroot` composer was failing, hence why it was removed. I'm very open to adding it back in if it can be made to work though
> allow composer to run as root

- provision/provision-site.sh
Like https://github.com/Varying-Vagrant-Vagrants/VVV/commit/66255db193e651ddc27aff948c6ec3d0e8b8bb09#diff-f50dd38f9eac292b9fd1f9f36ccd8aa2 this tries to fix an issue some users have when cloning site templates
Related to https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1764
> Removed noroot from the site provisioners git commands

- provision/provision.sh
This fixes users seeing warnings that the mysql group and user already exists when reprovisioning
> only creates the mysql user and group if it doesnt already exist

- provision/provision.sh
This takes up at least 5 seconds of the core provisioner, and always runs. Now it only runs if it needs to
> only add the git ppa when it's missing

- Vagrantfile
This shouldn't be necessary, but for the moment this lets us turn off the DB shared folder, the raw DB data will be stored inside the VM. This does mean the DB gets destroyed on every box update though.
It also means that toggling this switch and reprovisioning will have strange behaviour
For example:
- if you provision, then turn it off, you'll get a new set of database files and a clean slate, none of the existing databases will be present, but they'll still be on the host in the database/data folder, they just wont be used
- If you then switched it off, it'd go back to using the database/data folder, but there would still be a database in the VM that's silenced and innaccessible
This still needs testing
> add an option to vvv-custom.yml to turn off db shares

- Vagrantfile
This fixes an issue some users had on provisioning VVV 3, it also bumps the minimum version of Vagrant to the latest ( v2.2.4 )
> Disable the vbguest plugin and bump minimum vagrant version to 2.2.4

- CHANGELOG.md
- Vagrantfile
- config/memcached-config/memcached.conf
- config/php-config/php7.2-custom.ini
- config/php-config/php7.2-fpm.conf
- config/php-config/xdebug.ini
Use subfolders for php and memcached instead of the entire /var/logs folder, and map those subfolders rather than the entire logs directory
> use mapped subfolders for logs

- Vagrantfile
- database/sql/backups/readme.txt
move backups from the old location to the new location when the new location doesnt exist but the old one does
> Auto-move db backups folder

- Vagrantfile
- provision/provision-dashboard.sh
- provision/provision-site.sh
- provision/provision-utility-source.sh
- provision/provision-utility.sh
- provision/provision.sh
In this way the log is more simple to read and share.
> Copy all the provision output in a log file

- CHANGELOG.md
- database/sql/import-sql.sh
makes the sql import script create databases if they dont exist before importing
> SQL Import Script Improvements

- provision/provision.sh
Require that the folder in `/home/vagrant/.composer/cache` has the wrong permission so is enough to remove it and this patch fix everything.
> fix composer permission

- CHANGELOG.md
- provision/provision.sh
This avoids warnings when running vagrant ssh for some users
> give vagrant user ownership over profile files rather than root

- Vagrantfile
The database share was setup for VirtualBox, but didn't take into account HyperV or Parallels
> DB Share HyperV/Parallels Provider Fixes

- database/sql/import-sql.sh
The import script didn't work when the name of a database contains hyphens (e.g. `my-wp-db`). This change enclose the name with backticks, so names with hyphens are working.
> db import: support db names with hyphens

- database/sql/import-sql.sh
- provision/provision-site.sh
If a site has a site template in the config file, but the folder on the filesystem is not a git repository and already exists, git won't be able to clone the site template.
In this scenario, either the folder needs to be deleted, or the site template repo field removed
> change how the site provisioner checks for git repositories

- config/homebin/xdebug_on
Updates the `xdebug_on` script to touch/chmod the right file ( it moved ) and output more info about what it's doing
> Fixes xdebug log creation

- Vagrantfile
There's a TTY fix provisioner and a provisioner that sets up the `/vagrant` folder, this PR merges them together to give a minor improvement to speed/simplicity
> merged two shell provisioners

- provision/provision.sh
Grunt != grunt-cli
Grunt-cli is the command line tool and usually grunt is installed in the project itself  but we are installing it globally and we need it globally or on provision we will have this errors with other packages not installed.
> Add also grunt (not grunt-cli)

- config/php-config/xdebug.ini
xDebug require an option enabled to work without issues with auto_prepend_file parameter.
ref: https://xdebug.org/docs/all_settings
Fix: #1855
> fix for auto_prepend_file

- CHANGELOG.md
- config/homebin/db_backup
- config/homebin/vagrant_destroy
- config/homebin/vagrant_halt
- config/homebin/vagrant_suspend
Currently, any calls to the `db_backup` shell script are aborted due to the conditional check in this script. The documentation for the flag in vvv-config.yml speaks only to whether or not the DBs should be backed up during vagrant box state changes so I believe this conditional check should be pulled up to the vagrant_halt, vagrant_suspend, and vagrant_destroy shell scripts. This would allow users to manually backup databases using this convenient script without having to reprovision the box with the setting changed.
> Fixes #1859: Allow users to run db_backup manually regardless if `general.db_backup` is true or false

- config/apt-source-append.list
Switch to the v10 nodesource packages instead of 11, core needs 10 not 11
> use the v10 nodesource apt source and install Node

- config/php-config/xdebug.ini
As #1866 it is better to revert this value because we will avoid that tideways and xdebug run together.
> Revert auto_trace as disabled

- CHANGELOG.md
- config/homebin/xdebug_off
- config/homebin/xdebug_on
Make sure xdebug is on OR tideways, but never both related to #1866
> make sure xdebug OR tideways is enabled, never both

- CHANGELOG.md
- provision/provision.sh
use noroot with npm so it's installed to the vagrant folder rather than the root folder
> Fixes npm user

- CHANGELOG.md
- Vagrantfile
specify keep_colors so that people aren't alarmed by composer output being red but still being ok
related to #1799
> specify keep_colors on provision

- provision/provision.sh
I am testing it right now with https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop/pull/14
> fix #1876 - remove nvm

- config/nginx-config/sites/default.conf
Redirects `vvv` `vvv.dev` etc to `vvv.test`
closes #1869
> Redirects non vvv.test default domains to the vvv.test address

- CHANGELOG.md
- config/sshd_config
- provision/provision.sh
This attempts to fix #1867
To test, run:
```sh
git checkout origin fix/dbssh
vagrant provision
```
Then attempt to connect to the database from an SQL client on the host
> Enables password SSH auth, fixes #1867

- CHANGELOG.md
- Vagrantfile
The ownership should be now be `vagrant`
`drwxr-xr-x   2 vagrant vagrant  4096 Jun 29 22:15 vagrant`
> change ownership from root to vagrant for /vagrant

- Vagrantfile
Added a simple color reset to avoid branch_c bleeding over to the some other output.
> Reset color after printing splash (to avoid weird coloring after)

- provision/provision.sh
chown node modules folder before not after, and run npm as root
> chown node modules folder before not after, and run npm as root

- .editorconfig
remove trailing whitespace from .editorconfig
> remove trailing whitespace from .editorconfig

- Vagrantfile
Firstly, this update replaces the vmware_fusion and vmware_workstation provider options with a single vmware_desktop option for both versions of VMware, accepted by the new version of the Vagrant VMware plugin by Hashicorp (https://www.hashicorp.com/blog/introducing-the-vagrant-vmware-desktop-plugin) - requiring replacement of the plugin rather than just an upgrade, as well as installation of the Vagrant VMware Utility. The new plugin will still accept vmware_fusion and vmware_workstation as provider options, however, unifying these will simplify future development of support for the VMware provider.
The new plugin and utility have resolved intermittent issues with starting the vmnet devices on vagrant up.
Secondly, this update replaces the abandoned puphpet/ubuntu1804-x64 box with the …
> Support for VMware Desktop

- Vagrantfile
This adds a set of shared folder overrides for the VMware provider - removing the fmode and dmode settings.
I haven't been able to get it working with the use_db_share database/data/ folder for some reason. Will open an issue with a debug log for this.
> Fix shared folder settings for VMware

- provision/provision.sh
Remove noroot for grunt install, not just the update, and make logging a bit better.
I also don't trust the check to see if grunt is present, it needs double checking that it's ok
> Grunt changes

- Vagrantfile
Changed how the db_share_type was checked, and set its default value if undefined, to off
We know that off always works, so lets switch to that by default and avoid the support hassle for end users at the same time. Decisions not options! They can always opt into it in future
Additionally, the splash screen checked if the value was true, or anything else. The actual conditional checked if it was false, or anything else. Now both check if it's true or anything else for consistency
@TODO: Update the changelog before merge as this might cause issues for users who use the shared folder and run `develop`. We should also update this PR with a message telling people the value is undefined and what VVV is going to do by default and how to change it
> Changed db_share_type checks and defaults

- Vagrantfile
This code add an exception in case the yaml file is wrong with an alert.
Also a check if sistes is defined or not.
I am looking for other stuff to check :-)
PS: seems that my editor removed all the useless whitespaces
> YAML validation, fix #1745

- Vagrantfile
- vvv-config.yml
This adds support (and checks for the availabilty) for the [vagrant-disksize](https://github.com/sprotheroe/vagrant-disksize) plugin.
This will allow to bypass issues related to disk space issues when `db_share_type` is set to false, or if somebody just wants more space.
> Add support for vagrant-disksize plugin.

- config/mysql-config/vvv-core.cnf
fix #1925
This parameter is useful when we are doing database replications and other things that in a dev instance like that we are not using.
Also can improve the performance as suggested in the ticket itself.
> Disable Mysql binary logging

- provision/provision.sh
> Enable mailhog on all PHP instances

- provision/provision-site.sh
This makes the site provisioner check if the destination folder is not empty (meaning there's potential code there that could get destroyed).
If the folder doesn't exists, or if it's empty, it should allow to clone the repo in no problem.
> Allow to clone provisioner in an empty directory.

- CHANGELOG.md
- config/homebin/xdebug_off
- config/homebin/xdebug_on
- vvv-config.yml
php 7.4 support got merged into the utilities repo, so anybody with VVV 3.0+ can use it, this PR just makes it a little nicer, quality of life stuff
> add php74 to the default config

- provision/provision-site.sh
This partially addresses https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1922, and adds messages when starting and finishing provisioning.
There was already a message when provisioning should be skipped, but i wasn't able to test that, since whenever the skip_provisioning option is not false, the provisioner is not run at all.
In any case, I don't foresee any problems coming out of this.
> Add coloring to the site provisioner

- CHANGELOG.md
- Vagrantfile
This uses `umask` to attempt to replicate the default permissions set in VirtualBox as closely as possible. Some are identical, a couple have slightly different file permissions because of how `umask` works, but it doesn't seem to be causing any issues on my end so far.
This should hopefully resolve #1974
> Adjusted default permissions for vmware using umask

- CHANGELOG.md
- Vagrantfile
We have fixed where the /var/log was still available when using Hyper-V, so we removed it, and works now with no issues with MariaDB.
> removed /var/log/ for Microsoft Hyper-V, no need

- CHANGELOG.md
- Vagrantfile
Fixed the mounted folders for logs for parallels, and shared db folder mounts, also updated vmware accordingly.
Note that the shared DB folder mounts may not work, but they're prone to issues as is and it's off by default, so no change there
> Mounted folder fixes for Parallels, and shared DB support for Parallels and VMWare

- CHANGELOG.md
- provision/provision-site.sh
This attempts to pipe all site template provisioning to the log file, bypassing the terminal, needs testing and polish
> attempt to pipe all site provisioner output to the log files

- .gitignore
closes #1994 by ignoring `config/tideways.json`
> ignore tideways.json

- CHANGELOG.md
- provision/provision-site.sh
Switches to the faster/simpler bash based string substitution
> replace the escaping on site names so that they work agan with dots

- provision/provision-site.sh
Included in this PR is a small change to the `get_hosts()` function in the `provision/provision-site.sh` to allow multiple hosts to be included as part of the `server_name` directive in NGINX. This is useful for testing local installations which need to develop and / or test in tandem with domain mapping capabilities, either that provided in WordPress Core from 4.5 onwards or with a plugin.
It is achieved with the following changes;
* Switching `shyaml get-values` to `shyaml get-values-0` which returns a null-terminated string (to save from any potential confusion around newline characters).
* Piped in to `tr '\0' ' '` which replaces the null character with a space.
* Piped in to `sed 's/ *$//'` to trim the leading / trailing whitespace.
I have tested this with a single host and multiple …
> Change site provision to support multiple hosts in NGINX config

- provision/provision-site.sh
This fixes #2028.
Accepts php or any valid upstream in the /etc/nginx/upstreams directory.
Example output:
> Fix potentially broken nginx_upstream.

- config/homebin/is_utility_installed
- config/homebin/tideways_off
- config/homebin/tideways_on
- config/homebin/xdebug_off
- config/homebin/xdebug_on
- provision/provision-site.sh
- provision/provision.sh
This avoids some warnings being printed before when tideways was not installed. Eg:
And also adds specific tideways commands to turn it on or off.
Avoids the problem that was inherent of having tideways installed, that either xdebug or tideways needed to be turned on at any given point.
I've created a new command to check if a utility is installed. It was duplicated across the provisioners, so a command made sense.
> Improve tideways integration

- Vagrantfile
When using with Parallels and it is provisioning folders, it gets a permissions issue and can't create the Wordpress websites.
Changed the setup of the www sync folder to use the vagrant user as the owner and www-data as the group.
Changed the box that is used as parallels/ubuntu-18.04 does not exist and Parallels are not creating boxes anymore. They recommend using the bento ones.
> Parallels Permission issue provisioning WWW folders

- config/bash_aliases
- config/bash_profile
- provision/provision.sh
This fixes #2041 .
I've done research on how all the profiles are set up in Ubuntu, and Linux in general.
Here is the information that has been the most helpful for me:
https://unix.stackexchange.com/a/29811
I've also considered things on this answer:
https://askubuntu.com/a/866169
I've decided to move PATH changes, and overall autocomplete initialization to bash_aliases, which is executed in most shell types. Also copying the aliases (not the profile) to the root folder now to run on root.
I've tested this and works with no problem.
> Make bash commands available for root

- provision/provision-site.sh
Fixes a problem in the site provisioner
> use the full path to is_utility_installed in the site provisioner

- CHANGELOG.md
- provision/provision.sh
Reverts Varying-Vagrant-Vagrants/VVV#2054
`php-pcov` is causing issues that prevent PHP FPM from starting, reverting until the cause is identified
> Revert "added the pcov PHP extension to the core provisioner"

- config/php-config/php7.2-fpm.conf
This fixes FPM starting, unsure why it stopped with the  latest package, but here's a fix
> change the PHP fpm PID

- config/homebin/tideways_on
- provision/provision-site.sh
- provision/provision.sh
Addresses problem with SSL certificates not being correctly added into Nginx site configs described in issue #2072.
> Adjust the syntax of if statements calling the is_utility_installed script

- provision/provision.sh
This fixes an issue with the latest box (and also a couple of versions before), which didn't have a proper /root/.rnd file which is necessary for generating a certificate.
Seems to address #2072 , right now tls-ca is working for me without the change in syntax proposed in #2073 .
I got this error while provisioning from scratch with 3.2.0 and 3.3.0 with the latest box.
```
* Sign the certificate using the above private key...
Can't load /root/.rnd into RNG
139738907833408:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:98:Filename=/root/.rnd
```
> Generate .rnd file if it doesn't exist.

- CHANGELOG.md
- provision/provision.sh
Always force the root password to its documented default on provision, fixes #2076, and force copies a MySQL config in case updates need to be made in the future
> Always force the root password to its documented default

- CHANGELOG.md
- provision/provision.sh
Change the provisioned at timestamp format to something more readable, makes the log folder much easier to work with
> Change the provisioned at timestamp format

- config/bash_aliases
As 3.1.0 we are not using anymore nvm
> Remove nvm support in bash_alias

- CHANGELOG.md
- config/default-config.yml
vmware_workstation is broken as a provider. It needs to be replaced as an example in the default-config.yml file. vmware_desktop correctly loads the latest bento box  on VMWare Workstation and VMWare Fusion and is platform agnostic.
vmware_desktop brings the provider in line with the current VVV Vagrantfile and the labels on the bento box used by all of the alt providers: https://app.vagrantup.com/bento/boxes/ubuntu-18.04
The other providers are added as a convenience for hyperv and parallels users and virtualbox just to complete the list of optional providers even though currently it would only override itself.
I realize this is virtually identical to the previous pull request but take your pick: The first one corrects only the provider currently listed there. This is more convenient for …
> Replace expired vmware_workstation provider and add other providers to default-config.yml

- CHANGELOG.md
- Vagrantfile
The way the file is written is quite far from idiomatic ruby making things
unnecessarily difficult to read and there are tons of low-hanging cleanups waiting
to happen.
This just cleans things up with rubocop (using the defaults) to make actual code
cleanups smaller.
> Use rubocop to clean up Vagrantfile

- CHANGELOG.md
- provision/provision-network-functions.sh
- provision/provision.sh
This fixes #2098 by installing `ack-grep` via `apt`
> switch to apt for ack-grep installation

- CHANGELOG.md
- provision/provision-network-functions.sh
Brings a big performance improvement to the new checks, specifically wordpress.org domain checking.
> don't recurse when checking sites, fixes #2101

- config/homebin/vagrant_up
I did a clean provision, no errors on any logs. SSHd in and there was nothing on /vagrant/failed_provisioners.
So i noticed that we needed to use the `-z` flag to check if the `ls` is empty or not.
> Fix failure bear not working properly.

- provision/provision-network-functions.sh
- provision/provision.sh
Basically that, on the wording of the messages being displayed it states that provisioning is going to be aborted. So that's what we're going to be doing.
If we exit with code 1, then other provisioners don't run either.
> Actually abort provision if network issues arise.

- provision/provision-network-functions.sh
- --level is used when recursion is enabled, in this case, it's not.
- lets not write any files.
> Slight improvement on the network check

- provision/provision.sh
This is throwing an error on every provisioning complaining that /etc/init doesn't exist. This is because upstart existed in trusty (VVV 2) but not anymore in bionic (VVV 3).
> Remove deprecated code from trusty

- config/bash_aliases
- provision/provision.sh
I figured out how to remove the requirement for full paths on the provisioners for using utilities under homebin.
I've added a fix at the beginning of the provisioner which makes the paths available to sudo aswell (by adding the homebin path to the secure_path parameter on `/etc/sudoers`)
Also fixed the PATH additions on bash_aliases so that they don't have a trailing slash, and that we check first if the path we're adding is already included or not.
In order to test this, you can SSH in and do the following:
```
is_utility_installed
sudo is_utility_installed
sudo su
is_utility_installed
```
None of the above commands should throw any errors (after a provision of course since the fix is implemented there)
After this is fixed, I can do a separate PR to remove the full path requirement …
> Fix sudo homebin path

- provision/provision-helpers.sh
- provision/provision-utility.sh
This fixes an issue brought up by @tomjn , in which the utility provisioner printed more output than before #2116 .
After researching, I've realized that none of the site provisioners print any output (at all) before #2116 because they were executed as separate commands (in a child process) as opposed to being sourced into the current shell.
For now i'm opening this PR as a draft, but we should consider instead of doing this, to mod the utility provisioners to output things to stdout when needed, so that we still get messages like:
```
* Copying phpMyAdmin into place
* Cleaning up after phpMyAdmin
* phpMyAdmin setup complete
```
Which were not printed (but logged) before #2116 .
I'll do some research and maybe do this PR to vvv-utilities.
> Fix logs for utility provisioners.

- CHANGELOG.md
- Vagrantfile
hostsupdater sets our host files on the host OS, but the status of that project is unknown. It looks like the owner might have gone AWOL, and there are Windows issues sitting unfixed, PR's unreviewed, etc.
Given we have Windows users with issues ( see #2026 ), we should look into an alternative, this PR tries to swap hostsupdater for hostmanager, with a fallback to the original.
If you have both installed, hostsupdater will still try to add the `vvv` domain to the hosts file, I could find no way to eliminate this.
PR is currently working locally on an existing VM in MacOS with Virtualbox:
I'd like to see the results of testing this PR on Windows and Linux, in particular from those users with issues
* [xv] I've tested this PR with Vagrant **v2.2.7** and VirtualBox **v6.0.14** on **MacOS**
> Switch to vagrant-hostmanager

- provision/provision-helpers.sh
This fixes the issue reported on Slack regarding failed URL checks not properly displaying on the summary at the bottom.
> Fix issue with network check report

- config/bash_aliases
Without this, binaries for installed gems aren't available in path
> add gem binaries to Path if the folder exists

- CHANGELOG.md
- provision/provision.sh
fix https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2150
> fix #2150 dpkg frontend lock

- CHANGELOG.md
- provision/provision-helpers.sh
- provision/provisioners.sh
This is an attempt to fix #2173 and also clarify a bit of the process to pipe data to a file.
While researching this, i noticed there's a bug in the current implementation which is kind of a pain in the ass to fix, but was not introduced by my refactor.
This basically is a concurrency issue with tee. The way it currently works is that each output (stdout and stderr) are piped to FIFO queues, which is later fed to tee. The script only waits for the queue to be written, but not until tee finishes writing (appending actually) to the file. This is the reason that in some cases the log lines might be out of order, or in a weird situation. Link to an explanation of this [here](https://stackoverflow.com/questions/58035279/why-does-exectee-output-display-out-of-order/58036027#58036027).
I've …
> Avoid stdout on all provisioners (except main)

- provision/provision.sh
Install PHP 7.2 intl extension
Partial fix for #2178.
> install php7.2-intl extension

- CHANGELOG.md
- config/default-config.yml
- provision/provision.sh
This adds `nvm` as a core utility in default config. Its disabled by default and has to be enabled in config prior to provisioning VVV.
This PR also removes the code from `provision/provision.sh` which looks for and deletes `nvm` folder.
Ref: #2177 
Ref: https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/67
> Added NVM utility

- CHANGELOG.md
- README.md
- Vagrantfile
This branch add support for this new plugin.
* Use this branch for VVV (just change the plugin priorities on settings the hosts doesn't do anything dangerous for your instance)
* Download the gem from https://github.com/goodhosts/vagrant/releases/tag/1.0.0-beta4
* Install it on your pc with this cli command `vagrant plugin install vagrant-goodhosts-*.gem`
* Now do `vagrant up` of your VVV instance with this branch
* Check if the website works in your browser and if the hosts file in your system is changed
* Execute a `vagrant halt` and check if the hosts file in your system doesn't ave anymroe the new definition generated on up
Fix https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2136
> Vagrant goodhosts

- CHANGELOG.md
- provision/provision-site.sh
The idea of handling defaults is to handle empty strings, but if it's specifically set to empty, our old way of reading specific values fail
[Here's](https://github.com/0k/shyaml#handling-missing-paths) docs related to what I used
> shyaml has a "default" parameter on the command, use it

- provision/provision-site.sh
I wonder why the line above has #\# but this one didn't? This might resolve an issue reported in #2204, broken nginx configs when the TLS-CA isn't installed
> Missing escaping for sed on tls-ca utility

- CHANGELOG.md
- Vagrantfile
fix #2215, basically stop the execution of vagrant with an alert if the user is root or is running with root permission.
Require a bit of testing.
> Prevent use of sudo vagrant up, #2215

- CHANGELOG.md
- provision/provision.sh
as ticket #2210 this adds the command during provisioning to avoid any issues on provisioning of previous failed provisions.
> fix #2210, add dpkg --configure -a to main provisioner

- CHANGELOG.md
- config/apt-conf-d/99hashmismatch
- provision/provision.sh
Usually repository have the file in various version and gz is the default one that usually doesn't have troubles.
The majority of guides suggest doing a cleanup and to avoid other issue to define this default
Require some testing by the users with the issues and the others, just to test if everything works.
Fix: ##2208
> Remove APT list files and switch compress default

- provision/provision.sh
- Explicitly require stable version of composer on self update
- Explicitly prefer dist packages
- Remove mockery phpinvoker and the PHP reply boris package
- Update the required version of PHPUnit to `^7.5` to match cores `composer.json`
> adjust global composer dependencies

- provision/provision-site.sh
You cannot return from a sourced script, only from functions, so we should exit.
> Fix provision-site fail situations

- .github/workflows/blank.yml
- .github/workflows/vvv-provisioning.yml
- provision/provision-site.sh
- provision/tests/provisioners.sh
This is something i've been working over the weekend.
It will attempt to simulate the same environment the provisioners get inside the VM, so that it runs all the provisioners.
So far, this only runs the provisioners (using part of the refactor we've made a couple months ago) and make the full logs available for download as artifacts.
Ideally, we could add extra steps here with some sort of test suite as a separate PR.
------
Couple of things I tried and didn't work:
- Running this on an official ubuntu:18.04 docker image fails due to several reasons, the main ones being: no systemd available, and no access to /etc/hosts (as that's managed by docker)
- Running the provisioner from vagrant (full test), doesn't work because GH Actions doesn't allow a VM to run in a VM (due to lack of VT-x …
> GH Action - Run Provisioners

- CHANGELOG.md
- provision/provision-site.sh
This PR lets sites specify git repos and folders to clone them to.
For example, in theory this creates a VIP Go site with the VIP Go skeleton:
```yaml
vipone:
repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
hosts:
- vipone.test
git:
public_html/wp-content/:
repo: https://github.com/Automattic/vip-go-skeleton.git
overwrite: true # delete wp-content if it is not a git repo
public_html/wp-content/mu-plugins:
repo: https://github.com/Automattic/vip-go-mu-plugins.git
overwrite: true # delete wp-content/mu-plugins if it is not a git repo
forcepull: true # on provision hard reset, discard local changes, and pull down the latest version
```
> Site git folders

- config/homebin/db_backup
`default: /srv/config/homebin/db_backup: line 22: dbnames: No such file or directory`
This should fix this error
> fix dbnames no such file or directory

- CHANGELOG.md
- Vagrantfile
- provision/provision-site.sh
Allow hosts to default to the sitename, reducing the require config
This would basically allow something like this
```yml
sites:
wordpress-one:
repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
```
And this site will provision as `wordpress-one.test`
> Allow hosts yml property to default to the site name.

- provision/core/composer/provision.sh
Related to #2291, though we should switch to v2 once PHPCodesniffer and core work fine with it
> switch back to composer v1

- CHANGELOG.md
- provision/core/php/provision.sh
This changes the default PHP version to 7.3
> Use PHP 7.3 by default

- CHANGELOG.md
- provision/core/php/provision.sh
Use the PHP specific version of pcov instead of installing all of them, and only copy configs if the folder exists
This needs testing, once it's confirmed to work for an existing and a new VVV instance, we can port this to the utilities.
> Only install the PCov version we need, and other PHP install tweaks

- CHANGELOG.md
- provision/core/php/provision.sh
handle mailhog xdebug opcache and mailcatcher configs for all PHP versions in the main provisioner
> Improve php config installation

- CHANGELOG.md
- config/homebin/vagrant
If a user runs `vagrant ssh` then forgets and runs a `vagrant` command without exit it will say the command can't be found
Well no longer!
> Add a vagrant command to the guest VM

- Vagrantfile
Updates the splash to indicate when admin privs are missing on Windows, avoids the word colour so americans aren't offended, and adds the commit short hash to the splash so we know which commit of a branch they're on
> Splash screen extra info

- CHANGELOG.md
- config/homebin/vvv_restore_php_default
- config/nginx-config/nginx.conf
- config/nginx-config/sites/default.conf
- config/php-config/php-custom.ini
- config/php-config/php-fpm.conf
- config/php-config/php-www.conf
- config/php-config/upstream.conf
- provision/core/php/provision.sh
Changes the default PHP from 7.3 to 7.4
> Upgrade default PHP to v7.4

- provision/core/composer/provision.sh
- provision/core/phpcs/provision.sh
- provision/core/wp-cli/provision.sh
> fix(noroot): on utilities

- CHANGELOG.md
- www/default/phpinfo/index.php
- www/default/xdebuginfo/index.php
Moves `xdebug_info()` to its own file, per #2382
> Add Xdebug info button

- CHANGELOG.md
- provision/provision-site.sh
Fixes sites that have spaces in their names generating invalid certificate directives
> closes #2459 by wrapping TLS paths in quotes

- CHANGELOG.md
- Vagrantfile
Updates the warning when no hosts plugin is present and make it not sh…ow on the plugin command
> Fix host plugin checks on vagrant plugin list

- config/default-config.yml
- config/homebin/vagrant_destroy
- config/homebin/vagrant_halt
- config/homebin/vagrant_suspend
Somehow, we managed to merge a broken default config and nobody noticed. This is an emergency patch to fix it. A YAML node can't also be a tag.
> Emergency fix - broken default config

- CHANGELOG.md
- provision/provision-dashboard.sh
When specifying a custom branch for the dashboard repository, git can sometimes cause warnings because it hasn't fetched the remote data yet
> Fix git warnings when specifying a dashboard branch

- CHANGELOG.md
- provision/core/wp-cli/provision.sh
change WP CLI provisioning to remove the doctor subcommand and enforce the owner and permissions of the wp command
> Remove WP CLI Doctor and force permissions/ownership

- CHANGELOG.md
- provision/provision-dashboard.sh
Dashboard provisioning fails to update due to a popd and pushd that are the wrong way around
> Fix an error in dashboard updating

- CHANGELOG.md
- Vagrantfile
Updates the character that warns you the first provision is long to be a bear. 
Also updated the text, because previously, it suggests running  `vagrant up` if you only wanted to turn on VVV, but the first time you do a `vagrant up`, if you haven't provisioned, you'd see this message. So now it's a bit more clear hopefully.
I kept the output as inline in the Vagrantfile, but happy to split into a separate file if we want.
Also look how cute they are with their lil tea mug, even sitting on a little table
```shell
default: Running: inline script
default:     
default:                                       A full provision will take a bit.
default:     ▄▀▀▀▄▄▄▄▄▄▄▀▀▀▄          ▄   ▄    Sit back, relax, and have some tea.
default:     █▒▒░░░░░░░░░▒▒█         █   █
default:      █░░█░░░░░█░░█ …
```
> Time to make the long provisioning warning be a bear. (and also provide more accurate information)

- CHANGELOG.md
- Vagrantfile
Switch to the bento boxes to avoid folder mounting issues
> VirtualBox Bento Box Ubuntu 20.04

- .github/workflows/vvv-provisioning.yml
- provision/tests/macos-tests.sh
This tests provisioning in different scenarios with vagrant and virtualbox.
One issue i've noticed:
There seems to be some times where we get failures on the provisioners (likely product of a bad setup of the MacOS VM or something of the sort). Rerunning the actions typically get a valid result.
The error is something like follows:
>   Vagrant can't use the requested machine because it is locked! This
>   means that another Vagrant process is currently reading or modifying
>   the machine. Please wait for that Vagrant process to end and try
>   again. Details about the machine are shown below:
> 
>   Name: default
>   Provider: virtualbox
Again, just re running the action (which will run the 3 jobs again, since they're all part of the same workflow).
Didn't change the changelog, since …
> Test provisioning on vagrant, instead of a linux VM with docker.

- Vagrantfile
switch parallels M1 box and add a warning for vagrant disksize on Arm
> Parallels tweaks

- CHANGELOG.md
- Vagrantfile
Fixes #2559 
If the machine is an Arm machine, use parallels rather than Virtualbox and the provider default in the config
> #2559 use parallels as the default provider if it is an arm machine

- CHANGELOG.md
- provision/provision-site.sh
As it says on the tin; it appears there is a typo in the `provision-site.sh` to enable composer create-project to work properly when specified in the `config/config.yml`.
I noticed this issue experimenting with VVV as a development environment for [Grav](https://getgrav.org/) after using the [Drupal setup in the documentation](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/#drupal) as a template.
```yaml
sites:
vanillagrav:
skip_provisioning: false
description: "Grav Site"
repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
nginx_upstream: php74
folders:
public_html:
composer:
create-project: getgrav/grav
hosts:
- grav.test
custom:
wp_type: none
```
I didn't update the changelog to ensure I didn't cause an unnecessary merge conflict.
> Fixed a typo preventing composer create-project working

- CHANGELOG.md
- provision/core/composer/provision.sh
In the future we probably want to move the composer cache directory into a shared/mounted folder and do the same for this folder, but for now lets get things working again
> fix #2589 create and own /root/.local/share/composer

- provision/core/vvv/provision.sh
Ref: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2525
So the pinning of mariadb packages wasn't fixing the problem and investigating a bit is that we remove mysql-common but is required by mariadb to put aliases for mysql (and it is in the mariadb repository).
Removing that line let everything works with no problem.
> MariaDB APT fix

- CHANGELOG.md
- provision/core/wp-cli/provision.sh
Related to #2600, this doesn't fix WP CLI Doctor updating, but it means the provisioner will continue to run so it's a soft failure rather than a hard failure
> Adjust wp cli package updating so it doesn't fail the provisioner

- CHANGELOG.md
- provision/core/php/sources-ubuntu-bionic.list
- provision/core/php/sources-ubuntu-focal.list
- provision/core/vvv/sources-ubuntu-bionic.list
- provision/core/vvv/sources-ubuntu-focal.list
- provision/provision-helpers.sh
> Switch to the newer launchpad PPA domain with HTTPS

- CHANGELOG.md
- provision/core/vvv/provision.sh
This fix an issue with hash mismatch as disable the hardware optimization for hash calculation and use the software version that works always.
> Disable gcrypt hardware optimization as we are a VM

- CHANGELOG.md
- provision/provision-site.sh
This helps fix the wp develop site template
> Npm in site provisioners

- CHANGELOG.md
- config/homebin/db_backup
- database/sql/import-sql.sh
Adds more verbosity during importing, I am not sure if we can add more.
> feat(db): more verbosity on importing

- provision/provision-site.sh
This PR adds the full path to the vvv_restore_php_default script because it is not in the path when the script is executed.
> Fix #2634 - adding full path to vvv_restore_php_default in provision-site.sh

- CHANGELOG.md
- Vagrantfile
This replaces some `Vagrant.has_plugin?` checks  in the Vagrantfile with `config.vagrant.plugins.include?` as the latter is not available when the `Vagrantfile` is run in version 2.1.4 and newer of Vagrant.
There are other `Vagrant.has_plugin?` calls in the Vagrant file, but they don't seem to affect things in the same way. I can mend that in a separate PR, but I am not sure about the effectiveness, even if `config.vagrant.plugins.include?` seems more reliable.
See also: https://github.com/hashicorp/vagrant/issues/10161
> Fixing faulty Vagrant plugin check
