config/mysql-config/my.cnf
=> Update my.cnf for innodb_file_per_table = 1

provision/provision.sh
=> added phpcs default_standard to WordPress-Core

CONTRIBUTING.md, README.md
* Update documentation to reflect the use of the new `develop` branch for central development.
* Update HTTP links to HTTPS when supported.
=> [PR] Update contributing docs

CONTRIBUTING.md
=> Fix https WP links

CONTRIBUTING.md
=> Update broken license link

README.md
https://github.com/Varying-Vagrant-Vagrants/VVV/blob/master/provision/provision.sh#L593
=> Update version of phpMyAdmin

Vagrantfile
fix suggested by @twisty7867 in #517
SEE: http://foo-o-rama.com/vagrant--stdin-is-not-a-tty--fix.html
=> fix-no-tty

README.md
This tripped me up and I've been using VVV for months, so it may help others.
=> Added guidance r.e. provisioning 32bit boxes on older hardware

Vagrantfile
As per documentation:
http://docs.vagrantup.com/v2/virtualbox/configuration.html
http://parallels.github.io/vagrant-parallels/docs/configuration.html
=> Add default CPU cores

provision/provision.sh
=> load phpmyadmin from new location

provision/provision.sh
Load the .tar.gz from GitHub
____
Resolves #589
=> load phpMemcachedAdmin from its new home on GitHub

README.md
Rather than provide a more stylish dashboard, we should leave the
decision to others as to what kind of dashboard they're looking for.
See #333, #609
Fixes #637
=> [PR] Add custom dashboards to documentation in README

.gitignore, provision/provision.sh
I had accidentally merged some changes to master that should have been PRs against develop due to the self-introduced confusion of the develop branch process. :)
Using this PR to clean things up.
=> [PR] Fix Develop branch with changes in master

Vagrantfile
I introduced a bug in #706. Oops. :)
=> [PR] Remove unused "give the box a name" section

provision/provision.sh
=> Avoid browser warnings for "site URL does not match SSL certificate."

README.md
The introductory note is a bit repetitive — tried to boil this down to the essence.
=> Iron out wording of introductory note.

README.md
=> Document `develop_git` command for switching from SVN repo to Git mirror

.gitignore
Helps to ignore log files generated by https://github.com/Varying-Vagrant-Vagrants/vvv-multisite
=> Ignore log files in subdirs as well

provision/provision.sh
if the vm is already provisioned, delete `/srv/www/default/database-admin` and run `vagrant provision`
=> updated phpMyAdmin to version 4.6.0

provision/provision.sh
@jeremyfelt Thanks for your praise on my last pull request. It was actually the first time I've ever done a pull request. Contributing to open source projects is fun!
=> modify brackets to match existing code style

README.md
Adding my VVV Material Dashboard project to the README. Thanks.
=> Added VVV Material Dashboard

config/mysql-config/my.cnf
Makes it about a gazillion times faster.
=> Enable query cache by default

provision/provision.sh
This is #878 with an additional commit.
=> [PR] Link `phpcbf` and `phpcs` to `/usr/local/bin`

provision/provision.sh
This fixes #872 by switching the installation of git from the default apt-get package to the ppa repo, ensuring the latest version.
=> Swaps git installation to ppa repo

provision/provision.sh
=> Add SSH2 PHP Extension

provision/provision.sh
=> Add BCMath PHP Extension

README.md, config/homebin/db_restore
Back when we switched the primary branch from `master` to `develop`, there were a few pull requests open against `master` that I merged without looking. :astonished: 
I *thought* I had resolved all that earlier, but after merging `develop` into `master` for 1.4.0 and comparing, I see that these 2 commits never made it back to `develop`.
So here we are. :)
=> [PR] Update develop with missing commits from master

ISSUE_TEMPLATE.md
I used the helpful (MIT licensed) guide from https://github.com/TalAter/open-source-templates to create a basic template and then expanded some of the text.
Fixes #1051.
=> [PR] Add an initial issue template for new issues

provision/provision-site.sh
=> Clone repos recursively in new provisioning system.

vvv-config.yml
Closes Varying-Vagrant-Vagrants/VVV#1068
=> Update vvv-config.yml to match changes made in #1068

README.md, docs/en-US/index.md
This is #1073 for the develop branch.
=> Merge documentation structure change to develop

README.md
It appears I stripped this out accidentally when maneuvering, slicing, and dicing. :)
=> [PR] Reintroduce text on VVV creation to main README

provision/provision-site.sh
=> add get_hosts and get_primary hosts functions

docs/en-US/default-credentials.md
Also display MySQL u/p on separate lines for consistency.
=> Add default root password of Vagrant box

docs/en-US/php-extensions.md
This merges existing documentation from the varyingvagrantvagrants.org
repository.
=> [PR] Add php-extensions.md from vvv docs repository

.github/CONTRIBUTING.md, CHANGELOG.md, docs/en-US/adding-a-new-site/changing-php-version.md, docs/en-US/adding-a-new-site/custom-domains-hosts.md, docs/en-US/adding-a-new-site/custom-paths-and-folders.md, docs/en-US/adding-a-new-site/index.md, docs/en-US/adding-a-new-site/migrating-vvv1.md, docs/en-US/adding-a-new-site/nginx-configs.md, docs/en-US/adding-a-new-site/setup-script.md, docs/en-US/basic-usage.md, docs/en-US/built-in-wp-installs.md, docs/en-US/default-credentials.md, docs/en-US/governance.md, docs/en-US/history.md, docs/en-US/installation/software-requirements.md, docs/en-US/php-extensions.md, docs/en-US/troubleshooting.md, docs/en-US/vm_config.md, docs/en-US/vvv-config.yml.md, docs/en-US/what-is-vvv.md
This makes things much cleaner in production
=> [PR] Add trailing slashes to permalinks in docs

docs/en-US/index.md
We can trim some of this out because it will be available in
other places.
=> [PR] Start tuning the main documentation page a bit

docs/en-US/migrating-vvv1.md
=> Minor typo in migrating-vvv1.md

docs/en-US/adding-a-new-site/index.md
=> Fix link to Nginx Configs page

docs/en-US/adding-a-new-site/index.md
=> link correction in docs

docs/en-US/adding-a-new-site/index.md
A recent PR was made against master, this brings that back into develop.
=> [PR] Align master/develop commits

docs/en-US/adding-a-new-site/index.md
Explain how to create vvv-custom.yml for the first time, as described in more detail at https://tomjn.com/2017/01/16/whats-new-vvv-2-0/
=> How to create vvv-custom.yml for the first time

www/default/index.php
=> open links on the dashboard in new tabs wiht target="_blank"

docs/en-US/adding-a-new-site/changing-php-version.md, docs/en-US/adding-a-new-site/custom-domains-hosts.md, docs/en-US/adding-a-new-site/custom-paths-and-folders.md, docs/en-US/adding-a-new-site/index.md, docs/en-US/adding-a-new-site/nginx-configs.md, docs/en-US/adding-a-new-site/setup-script.md, docs/en-US/index.md
Not all documentation is accessible at the moment, they were written on the assumption there'd be a main navigation on the left to click through. That isn't the case however, so I've added some to the adding a new site section, expanded the main page links, and filled in one or two TODO items
=> Docs update

Vagrantfile
- No Sound
- Display Memory
- Clipboard and drag&drop
- Other hardware glips
=> Add additional properties to virtualbox

www/default/index.php
Adds a link to the add new site docs under the bundled environments list
=> Dashboard Add New Site link

Vagrantfile
=> Name VirtualBox from Vagrant folder and path hash

docs/en-US/adding-a-new-site/changing-php-version.md, docs/en-US/adding-a-new-site/custom-domains-hosts.md, docs/en-US/adding-a-new-site/custom-paths-and-folders.md, docs/en-US/adding-a-new-site/index.md, docs/en-US/adding-a-new-site/nginx-configs.md, docs/en-US/adding-a-new-site/setup-script.md, docs/en-US/index.md, docs/en-US/references/default-sites.md, docs/en-US/utilities.md
Fixes the links at the top of the adding a new site section of the docs, and adds a utilities page documenting how they work
=> Fix links and Add Utilities docs

docs/en-US/adding-a-new-site/changing-php-version.md, docs/en-US/adding-a-new-site/custom-domains-hosts.md, docs/en-US/adding-a-new-site/custom-paths-and-folders.md, docs/en-US/adding-a-new-site/index.md, docs/en-US/adding-a-new-site/nginx-configs.md, docs/en-US/adding-a-new-site/setup-script.md, docs/en-US/index.md
fixes a missing s in the links to the custom domains and hosts doc
Fixes #1257
=> Fix Broken Link

docs/en-US/adding-a-new-site/index.md
Clarify file structure and setup order:
* Separate out provision folder management from site files management
* Clarify files needed for provisioning
=> Clarify file structure and setup order

vvv-config.yml
This makes vvv-config.yml a bit friendlier and puts the most important docs directly in the file for people to refer to
=> adds comments to vvv-config.yml explaining things better

.gitignore
=> Ignore provision generated PHPCS files in Git

www/default/index.php
Readds the search box for the docs to the dashboard, and changes the URL to the new docs site
=> Dashboard Docs Search

Vagrantfile
See https://www.virtualbox.org/manual/ch10.html#gimproviders
Fixes #1233
=> Add a paravirtualization interface configuration for VirtualBox

Vagrantfile
By switching to this box VVV works again on Hyper-v.
Also solves #1082
=> Changes hyperv provider to a working one

provision/provision-utility-source.sh
=> Use `-q` option when installing/updating utility sources

provision/provision-site.sh
See #1336/#1337 for utility sources.
=> Use `-q` option when cloning/pulling site repos

provision/provision.sh
=> Improve updating nvm by not switching branches

config/homebin/xdebug_off, config/homebin/xdebug_on, provision/provision.sh
Related to #1263, #1342, Varying-Vagrant-Vagrants/vvv-utilities#11.
=> Always restart all php-fpm versions available in `/etc/init.d/`

www/default/index.php
Fixes https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1351
=> Fix TLD in new site example to match recommended VVV TLD

.gitattributes
=> Update .gitattributes to avoid bin CRLF conversion

www/default/index.php
Just pulled the latest version of the repo (develop branch).
`vvv.dev` was showing a php error.
This pull request fixes it.
=> Dashboard: Fix breaking typo

www/default/dashboard/php/blocks/main/bundled-environments-intro.php
There is a missing "in", in a sentence.
=>  Update bundled-environments-intro.php add missing text

LICENSE, README.md, Vagrantfile
=> sets the version branch correctlyin splash

provision/provision-site.sh, vvv-config.yml
Add a function to allow checking if a specific utility is installed from site provisioners
=> is_utility_installed provisioner function

config/homebin/vagrant_destroy, config/homebin/vagrant_halt, config/homebin/vagrant_suspend, config/homebin/vagrant_up
when custom bin script hooks are present, output to log that they're being ran
=> custom trigger hooks log

provision/phpcs/composer.json, provision/provision.sh
via issue #1455 adding PHPCompatibility
=> PHPCompatibility PHPCS standards

provision/provision.sh
=> Removes the legacy TLS certificate generation

config/mysql-config/my.cnf, config/nginx-config/nginx.conf
=> changes the mysql logs to use /srv/log instead of /var/log

Vagrantfile, config/homebin/vagrant_destroy, config/homebin/vagrant_halt, config/homebin/vagrant_suspend, config/homebin/vagrant_up, provision/provision.sh
Closes https://github.com/Varying-Vagrant-Vagrants/VVV/issues/710
=> Run scripts from vagrant mount

provision/provision.sh
Reverts Varying-Vagrant-Vagrants/VVV#1494
=> Revert "simplify the npm commands, closes #485"

provision/provision.sh
Reverts Varying-Vagrant-Vagrants/VVV#1508
reopens #1507
=> Revert "Fixes a warning, closes #1507"

config/bash_profile
related to https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1203#issuecomment-395109412
=> Update the PATH with the vagrant homebin folder

Vagrantfile, config/apt-source-append.list, provision/provision.sh
Attempts to simplify the package installing by letting apt-get check if they need updating when it goes to install them
The hope is that this is a faster way to do things
=> Simplify Package Installation

Vagrantfile
Shouldn't break anything but want to be sure, at a local user group so will test later
=> disable insert key, closes #1551

Vagrantfile
Closes #1550, needs testing on Windows, tested on MacOS
=> Tomjn splash info

provision/provision.sh
also expands the help to mention VPNs, props to @abrightclearweb
=> Switches network detection back to google.com

provision/provision.sh
=> Attempt to force answer the config questions from dpkg

Vagrantfile
Reverts Varying-Vagrant-Vagrants/VVV#1534
This can be re-applied once #1577 is resolved
=> Revert "Switch to vvv-base/ubuntu1404 for virtualbox"

provision/provision.sh
=> copies the mailhog ini for PHP in the default PHP setup script

provision/provision.sh
phpenmod mailhog not mailcatcher, and simplify the mailcatcher service cleanup
=> fix mailhog on startup

Vagrantfile
see https://github.com/hashicorp/vagrant/issues/7648
=> added a NAT workaround

CHANGELOG.md, provision/provision-site.sh
if no nginx config is found for a site, mention it in the provisioner log, also reduce the search depth from 4 to 3
=> Site Provisioner Improvements

CHANGELOG.md, Vagrantfile
This should improve hyperV and parallels compatibility, as well as compat with Ubuntu boxes that don't have an ubuntu user
=> changes the owner of the log folder from ubuntu to vagrant

CHANGELOG.md, config/apt-source-append.list
=> switch from Node v6 to Node v10

vvv-config.yml
Related to #1649 but also adds comments and renames the default sites, and adds a second standard WP install, anda  commented out example
=> A better starting configuration

provision/provision.sh
=> clean up the utility nginx folder so that stale configs get cleaned up

provision/provision.sh
This force copies over some files so that they're always the latest. This way on reprovision old things get cleared out and new changes are enforced
=> Force copy files in main provisioner

config/nginx-config/nginx-wp-common.conf
Fixing Getting error net::ERR_INCOMPLETE_CHUNKED_ENCODING #324
=> Fixing Getting error net::ERR_INCOMPLETE_CHUNKED_ENCODING

Vagrantfile
=> set locale, fix #1733

provision/phpcs/composer.json
Hello Team,
I have changed name to lowercase for solve bug of #1740. Please review it.
Thanks
=> solved Composer 2.0 warning #1740

CHANGELOG.md, Vagrantfile, config/homebin/vagrant_provision, config/homebin/vagrant_up
Make the vagrant up script a little friendlier, and a little more obvious when the process has finished
Makes it a bit clearer when `vagrant up` has finished and not aborted
=> Homebin Messaging Improvements

README.md
Very minor typo change in the readme.md
=> Readme: Fix minor typo

database/sql/import-sql.sh
That var doesn't exist because it is an error
=> Fix typo and use right var in import_sql

database/sql/import-sql.sh
Just fixes the message in the import script. It creates the *database*, not the *table*, no?
=> Fix message in import script

config/bash_profile
=> remove reference to go

Vagrantfile, provision/provision.sh
=> run the tty fix as a priviledged user

provision/provision.sh
add php-yaml for https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/25
=> Add php-yaml module

vvv-config.yml
=> add doc for tideways in config.yml

CHANGELOG.md, provision/provision.sh
=> fix #1880 - downgrade nodejs 11

.editorconfig
=> fix #824 - editorconfig

vvv-config.yml
Add the new parameters from https://github.com/Varying-Vagrant-Vagrants/custom-site-template/pull/16 and https://github.com/Varying-Vagrant-Vagrants/custom-site-template/pull/14
=> Update vvv-config to support the new parameters on custom-template

Vagrantfile
- don't erase the entire folder, just the files that are needed
- only symlink certificates if it hasn't been done already
- chmod the 3 files that were copied over so they're definitely readable
=> update how the /vagrant folder is provisioned

vvv-config.yml
Dont install tideways/memcached/webgrind etc by default, just phpmyadmin and the TLS certificate authority
=> Simplify default config

.github/labeler.yml, .github/workflows/label.yml
=> labeller action for PRs

database/data/README.md, database/data/readme.txt
Also formats in markdown, adds capitals when needed.
=> Uses the same name as the file in the other directories

config/apt-source-append.list
=> switch apt mirrors/sources from http to https

config/apt-source-append.list
=> Revert to http for launchpad

CHANGELOG.md, config/init/vvv-start.conf, provision/provision.sh
Installs additional NTP packages
=> install additional NTP packages and restart the service

CHANGELOG.md, Vagrantfile
removed unnecessary then statements on if conditionals in the vagrant file
=> remove Vagrantfile then conditionals

database/sql/import-sql.sh, provision/provision-dashboard.sh, provision/provision-network-functions.sh, provision/provision-site.sh, provision/provision-utility-source.sh, provision/provision.sh
Fixes some issues flagged by Codacy
=> Codacy shell script fixes

database/sql/import-sql.sh
fixes  predot being prefixed with `./`,  also  adjusted variable names and some syntax
=> Fix import SQL script

Vagrantfile
As title so https://gist.github.com/Mte90/9810f7c2775f1fd79ee049b3d259dff0 works
=> Expose vvv_config to Customfile

CHANGELOG.md, provision/provision.sh
=> added the pcov PHP extension to the core provisioner

provision/provision.sh
Activates MailHog for PHP CLI, and improves some logging
=> Fixes #2048 and improves log messages

README.md
=> Bump virtualbox and vagrant version supported

CHANGELOG.md, provision/provision-network-functions.sh
Refactor how network connections are checked to check more domains and update text
=> Refactor network checks

provision/provision.sh
Tries to fix mysql root user/pass correction, printing out more info, and stopping the database when it's in safe mode
=> refactor how the mysql root password is fixed and the service is stopped

provision/provision-site.sh
move more of the site provisioner into functions and reorder how they're called
=> Refactor site provisioner

provision/provision.sh
Just scrutinizing the code for potential cleanup, found this. Seem to have been introduced roughly a month ago, so it's not something critical.
=> Random typo fix

CHANGELOG.md, config/apt-source-append.list, provision/provision-helpers.sh
Attempts to add more MariaDB mirrors for various locations around the world
=> Fix/1993 MariaDB Apt Mirrors

CHANGELOG.md
This should make clear the changes we've introduced.
I think i didn't miss anything. I know this is a change in how we've been structuring the changelog, but i think it's useful to link to the PRs of each change to more easily track changes.
Let me know if this is useful.
=> Update changelog, linking to PRs of each change.

CHANGELOG.md, config/homebin/vagrant_up, provision/provision.sh
=> Fix invalid oh noes issues and add extra info to it

Vagrantfile
Detect windows and ignore for warning
=> Ignore windows user for administration warnings

CHANGELOG.md
This updates the changelog for PR #2231
=> Update changelog for #2231

CHANGELOG.md, provision/provision.sh
Remove the searching subfolders for old SVN repositories that need upgrading to the newer SVN repo format
=> Remove svn upgrade check

provision/core/deprecated.sh, provision/core/env.sh, provision/core/mariadb/provision.sh, provision/core/php/provision.sh
I've found some issues while experimenting with docker provisioning, and here are some minor fixes/gotchas
Also, i've rearranged the PHP provisioner and moved anything memcached to it's own section at the bottom, so it's easier to move to another provisioner in the future.
Ideally memcached could be turned into an optional utility, that you could choose among others, eg: redis.
=> Minor cleanup changes

CHANGELOG.md
Simply a changelog update to my last 2 PRs.
=> Changelog change for #2230 and #2238.

CHANGELOG.md, provision/provision-dashboard.sh
Also adjusts git clone to match site template
=> add noroot to dashboard provisioner

Vagrantfile
=> Fixed url to vagrant plugin

CHANGELOG.md, config/homebin/db_backup
- counts the number of databases and shows progress
- refactored how database names are collected and skipped
- aligned database names
=> Db backup output improvements

CHANGELOG.md, provision/core/wp-cli/provision.sh
Ref: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2051
=> Install wpcli doctor package, fix #2051

wp-cli.yml
=> add ssh parameter to the WP CLI config

wp-cli.yml
Reverts Varying-Vagrant-Vagrants/VVV#2265
=> Revert "add ssh parameter to the WP CLI config"

config/homebin/box-cleanup.sh, config/homebin/box-minimize.sh, provision/core/composer/provision.sh, provision/core/php/provision.sh, provision/provision-helpers.sh
box creation related improvements
=> box tweaks

config/homebin/vagrant_up
Ref: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2217
=> NTP updates, fix #2217

Vagrantfile
This fixes the issue reported in #2284 ( introduced in #2267 ).
=> Fix hosts mapping not working after #2267

config/homebin/vagrant_up
Fixes error introduced in #2283
=> Use "insecure" ports to do ntpdate

provision/core/vvv/provision.sh
Trying a fresh provision today, and shyaml wasn't installing.
After this, it provisions and work fine. Not sure of the details of the error (likely a change upstream somewhere).
=> Fix syhaml not working

CHANGELOG.md, provision/core/wp-cli/provision.sh
This might make this code more robust
=> Use HTTPS instead of SSH for WP CLI Doctor

provision/core/nodejs/provision.sh, provision/core/nodejs/sources.list
=> Node v14 LTS

provision/core/deprecated.sh, provision/core/env.sh, provision/core/git/provision.sh, provision/core/mailhog/provision.sh, provision/core/mariadb/provision.sh, provision/core/nginx/provision.sh, provision/core/php/provision.sh, provision/core/vvv/provision.sh, provision/core/wp-cli/provision.sh, provision/provision-helpers.sh, provision/provision.sh, provision/tests/run-provisioners.sh
This attempts to make our provisioners a little more comfortable during docker builds. Note that this PR is not adding docker support.
=> Docker compatibility adjustments

provision/core/nodejs/provision.sh
Be a little more thorough when forcing the Node version to 14
=> Update Node apt commands

provision/core/nodejs/provision.sh
if /usr/bin/npm does not exist, purge and reinstall nodejs
Might fix #2249
=> Attempted fix of missing npm

provision/provision-helpers.sh
The Nodesource PPA is needed, so we should check for it
This may help in debugging #2349
=> Add Nodesource PPA to the network checks

provision/core/nodejs/provision.sh
There is a double install so there is an error on provisioning.
=> Fix nodejs installation

CHANGELOG.md, provision/core/php/provision.sh
Installs the missing package for Xdebug support
=> Installs the missing package for Xdebug support

CHANGELOG.md, provision/provisioners.sh
Fix https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2096
=> Print current log file in case of error

provision/core/phpcs/provision.sh
=> dont create phpcs symlinks

CHANGELOG.md, provision/provision-helpers.sh, provision/provision-site.sh
expand and improve the logging in the site provisioner, with clearer messages and new messages
=> Better site provision messaging, and fixed git cloning

CHANGELOG.md, provision/core/composer/provision.sh
=> Upgrade to composer v2

CHANGELOG.md, provision/core/nodejs/nodesource-ppa-pin, provision/core/nodejs/provision.sh, provision/core/php/ondrej-ppa-pin, provision/core/php/provision.sh
Pins Ondrej PPA and Nodesource
=> attempt to pin nodesource and ondrej

provision/provision-helpers.sh
=> Ensure lockfiles exist before trying to remove them

CHANGELOG.md, provision/core/mailhog/provision.sh
Title says it all, fixes #2423
=> Add ARM64 support for Mailhog

provision/core/mailhog/provision.sh
=> Better Mailhog download handling

CHANGELOG.md, Vagrantfile
This PR adds the Arm M1 box for parallels users on Apple Silicon
=> Add a box for Apple M1 support

CHANGELOG.md, config/default-config.yml
=> Disable backup and restore of databases by default

.github/workflows/vvv-provisioning.yml, CHANGELOG.md, provision/core/composer/provision.sh
=> Cleanup Composer installation

CHANGELOG.md, provision/core/mailhog/provision.sh
better messages, upgraded to 1.0.1, always copy the service file
=> MailHog tweaks

CHANGELOG.md, Vagrantfile
=> Update to Ubuntu 20.04

CHANGELOG.md, provision/core/vvv/provision.sh
in theory this will enable webp support in imagick
closes #2457
=> Webp support

provision/core/vvv/provision.sh
=> Try to fix mariadb installation on GH action

config/default-config.yml
=> Add to default-config.yml stuff from #2346

CHANGELOG.md, provision/core/grunt/provision.sh
This _might_ fix #2476, we should confirm that it doesn't break anything first for existing or new users
=> maybe avoid npm symlink issues when updating grunt see #2476

CHANGELOG.md, Vagrantfile
Based on https://github.com/laravel/homestead/pull/63
=> Force 64bit in vagrantfile under virtualbox

CHANGELOG.md, config/php-config/php-custom.ini
update memory_limit from 128M to 256MB
=> update memory_limit from 128M to 256M

CHANGELOG.md, config/homebin/vagrant_up, provision/provision.sh
=> Run ntpupdate if it's available, and at a much earlier stage

provision/core/wp-cli/provision.sh
=> Turn off xdebug before wp package install and update wp packages

config/homebin/switch_php_debugmod
Explicitly disable FPM and CLI instead of implicitly all
=> Adjust phpmod disabling

CHANGELOG.md, Vagrantfile
Fix https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2224
=> Skip_provisioning support for vm_dir and local_dir

CHANGELOG.md, provision/core/vvv/provision.sh
=> 2513 - Unattended Apt package upgrades

CHANGELOG.md, Vagrantfile, database/sql/import-sql.sh, provision/core/composer/provision.sh, provision/core/env/homedir/.bash_aliases, provision/core/grunt/provision.sh, provision/core/nodejs/provision.sh, provision/core/wp-cli/provision.sh, provision/provision-helpers.sh, provision/provision-tools.sh, provision/provision.sh
=> Tools Provisioner

provision/core/vvv/provision.sh
=> adding libgnutls30 package

.gitignore, provision/core/nodejs/sources-ubuntu-bionic.list, provision/core/nodejs/sources-ubuntu-focal.list, provision/core/vvv/provision.sh, provision/provision.sh
=> Force ca certificates package

CHANGELOG.md, database/sql/import-sql.sh
Fix https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2546
=> fix(db): importing when excluded

CHANGELOG.md, config/homebin/vagrant_provision, config/homebin/vagrant_up, config/init/vvv-start.conf, provision/core/git/provision.sh, provision/core/mariadb/provision.sh, provision/core/mariadb/sources-ubuntu-focal.list, provision/core/vvv/provision.sh, provision/provision-helpers.sh, provision/provision.sh
This reduces some of the work needed for the docker PR #2537
=> WIP docker compat enhancements

CHANGELOG.md, provision/provision-site.sh
Don't check for the TLS CA, check for the presence of the certificate instead
=> Certificate file checking

CHANGELOG.md, Vagrantfile, config/wordpress-config/wp-tests-config.php, provision/core/memcached/config/memcached.conf
Updates virtualbox private ip adress to "192.168.56.4" #2567
=> Update virtualbox private ip address 

CHANGELOG.md, provision/provision-helpers.sh
as title, so we can avoid issues reported for that
=> Updated mariadb mirror for connectivity check

config/homebin/switch_php_debugmod, provision/core/composer/provision.sh, provision/core/env/provision.sh, provision/core/grunt/provision.sh, provision/core/phpcs/composer.json, provision/core/phpcs/provision.sh, provision/core/wp-cli/provision.sh, provision/provision-helpers.sh, provision/provision-tools.sh
=> Expand the composer installation steps output and checks

provision/core/node-nvm/provision.sh
=> Fix git error on nvm

Vagrantfile
=> Add ruby version in logs

provision/core/vvv/provision.sh
=> missing mkdir -p parameter

database/sql/import-sql.sh
Seems that the issue is still there, I didn't noticed the error the other day...
=> Fix unbound variable part 2

Vagrantfile, database/sql/init.sql, provision/core/mailhog/provision.sh, provision/core/mariadb/provision.sh, provision/provision-helpers.sh
=> More docker compatibility tweaks

config/homebin/switch_php_debugmod
=> Better switch php debug mod compatibility with docker images

CHANGELOG.md, config/default-config.yml, config/homebin/vvv_restore_php_default, provision/provision-site.sh, provision/provisioners.sh
Ref: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2367
Part of: https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/pull/207
=> feat(php): Set PHP version per site

CHANGELOG.md, provision/provision-site.sh
=> php parameter fixes for sites
